2025-03-19 21:35:10,024 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-19 21:35:10,157 | DEBUG | app | API carregando banco: sqlite:///:memory:
2025-03-19 21:35:10,227 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-19 21:35:10,695 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-19 21:35:10,695 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-19 21:35:10,839 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-19 21:35:10,839 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-19 21:35:11,301 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-19 21:35:11,301 | INFO | routes.api.auth | Dados recebidos: {'email': 'user@email.com', 'password': '123456'}
2025-03-19 21:35:11,458 | INFO | ProdutoService | Utilizador user@email.com autenticado.
2025-03-19 21:35:11,460 | INFO | routes.api.auth | Utilizador autenticado: user@email.com
2025-03-19 21:35:11,903 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-19 21:35:11,903 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'teste errado'}
2025-03-19 21:35:12,033 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-19 21:35:12,033 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-19 21:35:12,464 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-19 21:35:12,465 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-19 21:35:12,595 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-19 21:35:12,595 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-19 21:35:12,598 | ERROR | routes.api.auth | Erro ao validar token: (builtins.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input.
[SQL: INSERT INTO tokens_revogados (token_jti, criado_em) VALUES (?, ?)]
[parameters: [{'token_jti': '83c7d122-dc99-4f4c-a3ee-a8fa831a0d6e'}]]
Traceback (most recent call last):
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1812, in _execute_context
    context = constructor(
              ^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 1477, in _init_compiled
    flattened_processors[key](compiled_params[key])
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\dialects\sqlite\base.py", line 1116, in process
    raise TypeError(
TypeError: SQLite DateTime type only accepts Python datetime and date objects as input.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\routes\api\auth.py", line 88, in logout
    TokenService.adicionar_token_na_blacklist(g.current_user["jti"])
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\services\tokenrevogadomanager.py", line 13, in adicionar_token_na_blacklist
    session.commit()
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2032, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4353, in flush
    self._flush(objects)
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4488, in _flush
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4449, in _flush
    flush_context.execute()
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
           ^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1818, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1812, in _execute_context
    context = constructor(
              ^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 1477, in _init_compiled
    flattened_processors[key](compiled_params[key])
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\dialects\sqlite\base.py", line 1116, in process
    raise TypeError(
sqlalchemy.exc.StatementError: (builtins.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input.
[SQL: INSERT INTO tokens_revogados (token_jti, criado_em) VALUES (?, ?)]
[parameters: [{'token_jti': '83c7d122-dc99-4f4c-a3ee-a8fa831a0d6e'}]]
2025-03-19 21:35:13,131 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-19 21:35:13,133 | INFO | routes.api.auth | Dados recebidos: {}
2025-03-19 21:35:13,133 | WARNING | routes.api.auth | Tentativa de login sem credenciais fornecidas.
2025-03-19 21:35:13,524 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-19 21:35:13,524 | INFO | routes.api.auth | Dados recebidos: {'email': 'naoexiste@email.com', 'password': '123456'}
2025-03-19 21:35:13,525 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: naoexiste@email.com
2025-03-19 21:35:13,525 | WARNING | routes.api.auth | Falha na autenticação para o email: naoexiste@email.com
2025-03-19 21:35:13,914 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-19 21:35:13,914 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'senhaerrada'}
2025-03-19 21:35:14,044 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-19 21:35:14,044 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-19 21:35:14,435 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-19 21:35:14,435 | INFO | routes.api.auth | Dados recebidos: {'email': 'email-invalido', 'password': '123456'}
2025-03-19 21:35:14,435 | WARNING | routes.api.auth | Tenativa de login de email envalido.
2025-03-19 21:35:15,220 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-19 21:35:15,220 | INFO | routes.api.auth | Formato de envio incorreto, não foi JSON
2025-03-19 21:35:16,786 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-19 21:35:16,786 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-19 21:35:16,913 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-19 21:35:16,914 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-19 21:35:16,916 | ERROR | routes.api.auth | Erro ao validar token: (builtins.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input.
[SQL: INSERT INTO tokens_revogados (token_jti, criado_em) VALUES (?, ?)]
[parameters: [{'token_jti': 'fbb37333-156a-4be0-82a3-83f601ee6037'}]]
Traceback (most recent call last):
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1812, in _execute_context
    context = constructor(
              ^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 1477, in _init_compiled
    flattened_processors[key](compiled_params[key])
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\dialects\sqlite\base.py", line 1116, in process
    raise TypeError(
TypeError: SQLite DateTime type only accepts Python datetime and date objects as input.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\routes\api\auth.py", line 88, in logout
    TokenService.adicionar_token_na_blacklist(g.current_user["jti"])
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\services\tokenrevogadomanager.py", line 13, in adicionar_token_na_blacklist
    session.commit()
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2032, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4353, in flush
    self._flush(objects)
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4488, in _flush
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4449, in _flush
    flush_context.execute()
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
           ^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1818, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1812, in _execute_context
    context = constructor(
              ^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 1477, in _init_compiled
    flattened_processors[key](compiled_params[key])
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\dialects\sqlite\base.py", line 1116, in process
    raise TypeError(
sqlalchemy.exc.StatementError: (builtins.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input.
[SQL: INSERT INTO tokens_revogados (token_jti, criado_em) VALUES (?, ?)]
[parameters: [{'token_jti': 'fbb37333-156a-4be0-82a3-83f601ee6037'}]]
2025-03-19 21:35:17,313 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-19 21:35:17,313 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-19 21:35:17,442 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-19 21:35:17,444 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-19 21:35:17,448 | INFO | CategoriaService | Categoria criada: Fruta
2025-03-19 21:35:17,448 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-19 21:35:17,448 | INFO | routes.api.categorias | Nova categoria criada Fruta
2025-03-19 21:35:17,840 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-19 21:35:17,840 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-19 21:35:17,968 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-19 21:35:17,969 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-19 21:35:17,971 | INFO | CategoriaService | Categoria criada: Categoria Teste
2025-03-19 21:35:17,971 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-19 21:35:17,971 | INFO | routes.api.categorias | Nova categoria criada Categoria Teste
2025-03-19 21:35:17,972 | INFO | ProdutoService | Parâmetros recebidos: nome=banana, preco=3.0, quantidade_estoque=10, categoria_id=2
2025-03-19 21:35:17,974 | ERROR | ProdutoService | Erro ao criar produto: (builtins.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input.
[SQL: INSERT INTO produtos (nome, descricao, preco, quantidade_estoque, ativo, categoria_id, criado_em, atualizado_em) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: [{'nome': 'banana', 'preco': 3.0, 'categoria_id': 2, 'quantidade_estoque': 10, 'ativo': True, 'descricao': None}]]
2025-03-19 21:35:17,976 | ERROR | produto_routes | Erro inesperado ao criar produto: Erro ao criar produto
2025-03-19 21:35:18,372 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-19 21:35:18,373 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-19 21:35:18,502 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-19 21:35:18,502 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-19 21:35:18,504 | INFO | produto_routes | Listando produtos ativos.
2025-03-19 21:36:22,468 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-19 21:37:21,452 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-19 21:37:21,504 | DEBUG | app | API carregando banco: sqlite:///:memory:
2025-03-19 21:37:21,533 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-19 21:37:21,937 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-19 21:37:21,938 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-19 21:37:22,070 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-19 21:37:22,070 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-19 21:37:22,073 | ERROR | routes.api.auth | Erro ao validar token: (builtins.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input.
[SQL: INSERT INTO tokens_revogados (token_jti, criado_em) VALUES (?, ?)]
[parameters: [{'token_jti': '2507391e-86cb-4551-b7d3-67a4bfd7db41'}]]
Traceback (most recent call last):
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1812, in _execute_context
    context = constructor(
              ^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 1477, in _init_compiled
    flattened_processors[key](compiled_params[key])
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\dialects\sqlite\base.py", line 1116, in process
    raise TypeError(
TypeError: SQLite DateTime type only accepts Python datetime and date objects as input.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\routes\api\auth.py", line 88, in logout
    TokenService.adicionar_token_na_blacklist(g.current_user["jti"])
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\services\tokenrevogadomanager.py", line 13, in adicionar_token_na_blacklist
    session.commit()
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2032, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4353, in flush
    self._flush(objects)
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4488, in _flush
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4449, in _flush
    flush_context.execute()
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
           ^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1818, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1812, in _execute_context
    context = constructor(
              ^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 1477, in _init_compiled
    flattened_processors[key](compiled_params[key])
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\dialects\sqlite\base.py", line 1116, in process
    raise TypeError(
sqlalchemy.exc.StatementError: (builtins.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input.
[SQL: INSERT INTO tokens_revogados (token_jti, criado_em) VALUES (?, ?)]
[parameters: [{'token_jti': '2507391e-86cb-4551-b7d3-67a4bfd7db41'}]]
2025-03-19 21:39:31,125 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-19 21:39:31,178 | DEBUG | app | API carregando banco: sqlite:///:memory:
2025-03-19 21:39:31,209 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-19 21:39:31,633 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-19 21:39:31,634 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-19 21:39:31,769 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-19 21:39:31,769 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-19 21:39:31,772 | ERROR | routes.api.auth | Erro ao validar token: (builtins.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input.
[SQL: INSERT INTO tokens_revogados (token_jti, criado_em) VALUES (?, ?)]
[parameters: [{'token_jti': 'b7aa89bd-28ed-4c27-ad77-e825d2fe0282'}]]
Traceback (most recent call last):
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1812, in _execute_context
    context = constructor(
              ^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 1477, in _init_compiled
    flattened_processors[key](compiled_params[key])
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\dialects\sqlite\base.py", line 1116, in process
    raise TypeError(
TypeError: SQLite DateTime type only accepts Python datetime and date objects as input.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\routes\api\auth.py", line 88, in logout
    TokenService.adicionar_token_na_blacklist(g.current_user["jti"])
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\services\tokenrevogadomanager.py", line 13, in adicionar_token_na_blacklist
    session.commit()
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2032, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4353, in flush
    self._flush(objects)
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4488, in _flush
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4449, in _flush
    flush_context.execute()
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
           ^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1818, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1812, in _execute_context
    context = constructor(
              ^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 1477, in _init_compiled
    flattened_processors[key](compiled_params[key])
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\dialects\sqlite\base.py", line 1116, in process
    raise TypeError(
sqlalchemy.exc.StatementError: (builtins.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input.
[SQL: INSERT INTO tokens_revogados (token_jti, criado_em) VALUES (?, ?)]
[parameters: [{'token_jti': 'b7aa89bd-28ed-4c27-ad77-e825d2fe0282'}]]
2025-03-19 21:41:03,663 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-19 21:41:03,714 | DEBUG | app | API carregando banco: sqlite:///:memory:
2025-03-19 21:41:03,744 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-19 21:41:04,144 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-19 21:41:04,144 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-19 21:41:04,276 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-19 21:41:04,278 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-19 21:41:04,281 | INFO | routes.api.auth | Logout com sucesso
2025-03-19 21:41:15,972 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-19 21:41:16,045 | DEBUG | app | API carregando banco: sqlite:///:memory:
2025-03-19 21:41:16,075 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-19 21:41:16,495 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-19 21:41:16,495 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-19 21:41:16,643 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-19 21:41:16,644 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-19 21:41:17,069 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-19 21:41:17,069 | INFO | routes.api.auth | Dados recebidos: {'email': 'user@email.com', 'password': '123456'}
2025-03-19 21:41:17,214 | INFO | ProdutoService | Utilizador user@email.com autenticado.
2025-03-19 21:41:17,214 | INFO | routes.api.auth | Utilizador autenticado: user@email.com
2025-03-19 21:41:17,683 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-19 21:41:17,683 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'teste errado'}
2025-03-19 21:41:17,904 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-19 21:41:17,905 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-19 21:41:18,424 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-19 21:41:18,424 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-19 21:41:18,579 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-19 21:41:18,579 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-19 21:41:18,586 | INFO | routes.api.auth | Logout com sucesso
2025-03-19 21:41:19,088 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-19 21:41:19,089 | INFO | routes.api.auth | Dados recebidos: {}
2025-03-19 21:41:19,089 | WARNING | routes.api.auth | Tentativa de login sem credenciais fornecidas.
2025-03-19 21:41:19,531 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-19 21:41:19,532 | INFO | routes.api.auth | Dados recebidos: {'email': 'naoexiste@email.com', 'password': '123456'}
2025-03-19 21:41:19,532 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: naoexiste@email.com
2025-03-19 21:41:19,533 | WARNING | routes.api.auth | Falha na autenticação para o email: naoexiste@email.com
2025-03-19 21:41:19,982 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-19 21:41:19,982 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'senhaerrada'}
2025-03-19 21:41:20,134 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-19 21:41:20,134 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-19 21:41:20,587 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-19 21:41:20,587 | INFO | routes.api.auth | Dados recebidos: {'email': 'email-invalido', 'password': '123456'}
2025-03-19 21:41:20,587 | WARNING | routes.api.auth | Tenativa de login de email envalido.
2025-03-19 21:41:21,478 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-19 21:41:21,478 | INFO | routes.api.auth | Formato de envio incorreto, não foi JSON
2025-03-19 21:41:23,230 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-19 21:41:23,231 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-19 21:41:23,380 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-19 21:41:23,380 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-19 21:41:23,382 | INFO | routes.api.auth | Logout com sucesso
2025-03-19 21:41:23,823 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-19 21:41:23,824 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-19 21:41:23,976 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-19 21:41:23,977 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-19 21:41:23,983 | INFO | CategoriaService | Categoria criada: Fruta
2025-03-19 21:41:23,983 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-19 21:41:23,983 | INFO | routes.api.categorias | Nova categoria criada Fruta
2025-03-19 21:41:24,424 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-19 21:41:24,424 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-19 21:41:24,574 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-19 21:41:24,575 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-19 21:41:24,577 | INFO | CategoriaService | Categoria criada: Categoria Teste
2025-03-19 21:41:24,577 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-19 21:41:24,577 | INFO | routes.api.categorias | Nova categoria criada Categoria Teste
2025-03-19 21:41:24,579 | INFO | ProdutoService | Parâmetros recebidos: nome=banana, preco=3.0, quantidade_estoque=10, categoria_id=2
2025-03-19 21:41:24,581 | ERROR | ProdutoService | Erro ao criar produto: (builtins.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input.
[SQL: INSERT INTO produtos (nome, descricao, preco, quantidade_estoque, ativo, categoria_id, criado_em, atualizado_em) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: [{'quantidade_estoque': 10, 'preco': 3.0, 'ativo': True, 'nome': 'banana', 'categoria_id': 2, 'descricao': None}]]
2025-03-19 21:41:24,581 | ERROR | produto_routes | Erro inesperado ao criar produto: Erro ao criar produto
2025-03-19 21:41:25,172 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-19 21:41:25,172 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-19 21:41:25,318 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-19 21:41:25,320 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-19 21:41:25,322 | INFO | produto_routes | Listando produtos ativos.
2025-03-20 11:16:05,704 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 11:16:06,020 | DEBUG | app | API carregando banco: sqlite:///:memory:
2025-03-20 11:16:06,115 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 11:16:07,245 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:16:07,245 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:16:07,582 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:16:07,583 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:16:08,603 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:16:08,604 | INFO | routes.api.auth | Dados recebidos: {'email': 'user@email.com', 'password': '123456'}
2025-03-20 11:16:08,989 | INFO | ProdutoService | Utilizador user@email.com autenticado.
2025-03-20 11:16:08,990 | INFO | routes.api.auth | Utilizador autenticado: user@email.com
2025-03-20 11:16:10,008 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:16:10,008 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'teste errado'}
2025-03-20 11:16:10,363 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-20 11:16:10,364 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-20 11:16:11,306 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:16:11,306 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:16:11,617 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:16:11,619 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:16:11,625 | INFO | routes.api.auth | Logout com sucesso
2025-03-20 11:16:12,679 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:16:12,679 | INFO | routes.api.auth | Dados recebidos: {}
2025-03-20 11:16:12,679 | WARNING | routes.api.auth | Tentativa de login sem credenciais fornecidas.
2025-03-20 11:16:13,692 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:16:13,692 | INFO | routes.api.auth | Dados recebidos: {'email': 'naoexiste@email.com', 'password': '123456'}
2025-03-20 11:16:13,694 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: naoexiste@email.com
2025-03-20 11:16:13,694 | WARNING | routes.api.auth | Falha na autenticação para o email: naoexiste@email.com
2025-03-20 11:16:14,747 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:16:14,747 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'senhaerrada'}
2025-03-20 11:16:15,051 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-20 11:16:15,052 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-20 11:16:16,055 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:16:16,056 | INFO | routes.api.auth | Dados recebidos: {'email': 'email-invalido', 'password': '123456'}
2025-03-20 11:16:16,056 | WARNING | routes.api.auth | Tenativa de login de email envalido.
2025-03-20 11:16:18,048 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:16:18,048 | INFO | routes.api.auth | Formato de envio incorreto, não foi JSON
2025-03-20 11:16:22,450 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:16:22,450 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:16:22,838 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:16:22,840 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:16:22,845 | INFO | routes.api.auth | Logout com sucesso
2025-03-20 11:16:24,080 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:16:24,080 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:16:24,495 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:16:24,496 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:16:24,509 | INFO | CategoriaService | Categoria criada: Fruta
2025-03-20 11:16:24,509 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:16:24,512 | INFO | routes.api.categorias | Nova categoria criada Fruta
2025-03-20 11:16:25,699 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:16:25,700 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:16:26,108 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:16:26,109 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:16:26,115 | INFO | CategoriaService | Categoria criada: Categoria Teste
2025-03-20 11:16:26,115 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:16:26,115 | INFO | routes.api.categorias | Nova categoria criada Categoria Teste
2025-03-20 11:16:26,118 | INFO | ProdutoService | Parâmetros recebidos: nome=banana, preco=3.0, quantidade_estoque=10, categoria_id=2
2025-03-20 11:16:26,124 | ERROR | ProdutoService | Erro ao criar produto: (builtins.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input.
[SQL: INSERT INTO produtos (nome, descricao, preco, quantidade_estoque, ativo, categoria_id, criado_em, atualizado_em) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: [{'nome': 'banana', 'categoria_id': 2, 'quantidade_estoque': 10, 'ativo': True, 'preco': 3.0, 'descricao': None}]]
2025-03-20 11:16:26,125 | ERROR | produto_routes | Erro inesperado ao criar produto: Erro ao criar produto
2025-03-20 11:16:27,914 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:16:27,917 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:16:28,310 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:16:28,312 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:16:28,317 | INFO | produto_routes | Listando produtos ativos.
2025-03-20 11:17:39,882 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 11:17:40,015 | DEBUG | app | API carregando banco: sqlite:///:memory:
2025-03-20 11:17:40,087 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 11:17:41,106 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:17:41,107 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:17:41,435 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:17:41,435 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:17:41,448 | INFO | CategoriaService | Categoria criada: Categoria Teste
2025-03-20 11:17:41,448 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:17:41,448 | INFO | routes.api.categorias | Nova categoria criada Categoria Teste
2025-03-20 11:17:41,451 | INFO | ProdutoService | Parâmetros recebidos: nome=banana, preco=3.0, quantidade_estoque=10, categoria_id=1
2025-03-20 11:17:41,457 | ERROR | ProdutoService | Erro ao criar produto: (builtins.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input.
[SQL: INSERT INTO produtos (nome, descricao, preco, quantidade_estoque, ativo, categoria_id, criado_em, atualizado_em) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: [{'categoria_id': 1, 'quantidade_estoque': 10, 'ativo': True, 'nome': 'banana', 'preco': 3.0, 'descricao': None}]]
2025-03-20 11:17:41,458 | ERROR | produto_routes | Erro inesperado ao criar produto: Erro ao criar produto
2025-03-20 11:17:47,326 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 11:17:47,463 | DEBUG | app | API carregando banco: sqlite:///:memory:
2025-03-20 11:17:47,528 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 11:17:48,506 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:17:48,506 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:17:48,818 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:17:48,819 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:17:48,831 | INFO | CategoriaService | Categoria criada: Categoria Teste
2025-03-20 11:17:48,831 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:17:48,832 | INFO | routes.api.categorias | Nova categoria criada Categoria Teste
2025-03-20 11:17:48,834 | INFO | ProdutoService | Parâmetros recebidos: nome=banana, preco=3.0, quantidade_estoque=10, categoria_id=1
2025-03-20 11:17:48,840 | ERROR | ProdutoService | Erro ao criar produto: (builtins.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input.
[SQL: INSERT INTO produtos (nome, descricao, preco, quantidade_estoque, ativo, categoria_id, criado_em, atualizado_em) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: [{'preco': 3.0, 'nome': 'banana', 'quantidade_estoque': 10, 'categoria_id': 1, 'ativo': True, 'descricao': None}]]
2025-03-20 11:17:48,841 | ERROR | produto_routes | Erro inesperado ao criar produto: Erro ao criar produto
2025-03-20 11:22:58,902 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 11:22:59,058 | DEBUG | app | API carregando banco: sqlite:///:memory:
2025-03-20 11:22:59,124 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 11:23:00,101 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:23:00,102 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:23:00,448 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:23:00,450 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:23:00,469 | INFO | CategoriaService | Categoria criada: Categoria Teste
2025-03-20 11:23:00,469 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:23:00,469 | INFO | routes.api.categorias | Nova categoria criada Categoria Teste
2025-03-20 11:23:00,473 | INFO | ProdutoService | Parâmetros recebidos: nome=banana, preco=3.0, quantidade_estoque=10, categoria_id=1
2025-03-20 11:23:00,482 | INFO | ProdutoService | Produto criado: banana, Preço: 3.0, Estoque: 10
2025-03-20 11:23:00,482 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:23:06,444 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 11:23:06,596 | DEBUG | app | API carregando banco: sqlite:///:memory:
2025-03-20 11:23:06,667 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 11:23:07,779 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:23:07,780 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:23:08,111 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:23:08,111 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:23:09,203 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:23:09,203 | INFO | routes.api.auth | Dados recebidos: {'email': 'user@email.com', 'password': '123456'}
2025-03-20 11:23:09,526 | INFO | ProdutoService | Utilizador user@email.com autenticado.
2025-03-20 11:23:09,526 | INFO | routes.api.auth | Utilizador autenticado: user@email.com
2025-03-20 11:23:10,641 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:23:10,641 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'teste errado'}
2025-03-20 11:23:11,011 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-20 11:23:11,011 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-20 11:23:12,187 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:23:12,187 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:23:12,532 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:23:12,532 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:23:12,538 | INFO | routes.api.auth | Logout com sucesso
2025-03-20 11:23:13,619 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:23:13,619 | INFO | routes.api.auth | Dados recebidos: {}
2025-03-20 11:23:13,620 | WARNING | routes.api.auth | Tentativa de login sem credenciais fornecidas.
2025-03-20 11:23:14,611 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:23:14,611 | INFO | routes.api.auth | Dados recebidos: {'email': 'naoexiste@email.com', 'password': '123456'}
2025-03-20 11:23:14,613 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: naoexiste@email.com
2025-03-20 11:23:14,613 | WARNING | routes.api.auth | Falha na autenticação para o email: naoexiste@email.com
2025-03-20 11:23:15,603 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:23:15,604 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'senhaerrada'}
2025-03-20 11:23:15,929 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-20 11:23:15,930 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-20 11:23:16,913 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:23:16,913 | INFO | routes.api.auth | Dados recebidos: {'email': 'email-invalido', 'password': '123456'}
2025-03-20 11:23:16,913 | WARNING | routes.api.auth | Tenativa de login de email envalido.
2025-03-20 11:23:18,810 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:23:18,811 | INFO | routes.api.auth | Formato de envio incorreto, não foi JSON
2025-03-20 11:23:22,902 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:23:22,902 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:23:23,223 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:23:23,223 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:23:23,226 | INFO | routes.api.auth | Logout com sucesso
2025-03-20 11:23:24,190 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:23:24,190 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:23:24,513 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:23:24,513 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:23:24,523 | INFO | CategoriaService | Categoria criada: Fruta
2025-03-20 11:23:24,523 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:23:24,523 | INFO | routes.api.categorias | Nova categoria criada Fruta
2025-03-20 11:23:25,489 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:23:25,489 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:23:25,807 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:23:25,807 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:23:25,813 | INFO | CategoriaService | Categoria criada: Categoria Teste
2025-03-20 11:23:25,813 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:23:25,813 | INFO | routes.api.categorias | Nova categoria criada Categoria Teste
2025-03-20 11:23:25,818 | INFO | ProdutoService | Parâmetros recebidos: nome=banana, preco=3.0, quantidade_estoque=10, categoria_id=2
2025-03-20 11:23:25,826 | INFO | ProdutoService | Produto criado: banana, Preço: 3.0, Estoque: 10
2025-03-20 11:23:25,827 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:23:26,918 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:23:26,919 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:23:27,285 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:23:27,285 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:23:27,288 | INFO | produto_routes | Listando produtos ativos.
2025-03-20 11:23:27,293 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:25:53,980 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 11:25:54,285 | DEBUG | app | API carregando banco: sqlite:///:memory:
2025-03-20 11:25:54,359 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 11:25:55,473 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:25:55,473 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:25:55,800 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:25:55,802 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:25:56,874 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:25:56,875 | INFO | routes.api.auth | Dados recebidos: {'email': 'user@email.com', 'password': '123456'}
2025-03-20 11:25:57,201 | INFO | ProdutoService | Utilizador user@email.com autenticado.
2025-03-20 11:25:57,201 | INFO | routes.api.auth | Utilizador autenticado: user@email.com
2025-03-20 11:25:58,374 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:25:58,374 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'teste errado'}
2025-03-20 11:25:58,685 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-20 11:25:58,685 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-20 11:25:59,681 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:25:59,682 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:26:00,021 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:26:00,022 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:26:00,030 | INFO | routes.api.auth | Logout com sucesso
2025-03-20 11:26:01,033 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:26:01,035 | INFO | routes.api.auth | Dados recebidos: {}
2025-03-20 11:26:01,035 | WARNING | routes.api.auth | Tentativa de login sem credenciais fornecidas.
2025-03-20 11:26:01,990 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:26:01,990 | INFO | routes.api.auth | Dados recebidos: {'email': 'naoexiste@email.com', 'password': '123456'}
2025-03-20 11:26:01,992 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: naoexiste@email.com
2025-03-20 11:26:01,992 | WARNING | routes.api.auth | Falha na autenticação para o email: naoexiste@email.com
2025-03-20 11:26:02,930 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:26:02,931 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'senhaerrada'}
2025-03-20 11:26:03,263 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-20 11:26:03,263 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-20 11:26:04,212 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:26:04,213 | INFO | routes.api.auth | Dados recebidos: {'email': 'email-invalido', 'password': '123456'}
2025-03-20 11:26:04,213 | WARNING | routes.api.auth | Tenativa de login de email envalido.
2025-03-20 11:26:06,123 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:26:06,123 | INFO | routes.api.auth | Formato de envio incorreto, não foi JSON
2025-03-20 11:26:10,190 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:26:10,191 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:26:10,488 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:26:10,489 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:26:10,492 | INFO | routes.api.auth | Logout com sucesso
2025-03-20 11:26:11,464 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:26:11,464 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:26:11,770 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:26:11,770 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:26:11,783 | INFO | CategoriaService | Categoria criada: Fruta
2025-03-20 11:26:11,784 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:26:11,784 | INFO | routes.api.categorias | Nova categoria criada Fruta
2025-03-20 11:26:12,752 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:26:12,752 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:26:13,058 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:26:13,058 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:26:13,068 | INFO | CategoriaService | Categoria criada: Categoria Teste
2025-03-20 11:26:13,068 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:26:13,068 | INFO | routes.api.categorias | Nova categoria criada Categoria Teste
2025-03-20 11:26:13,072 | INFO | ProdutoService | Parâmetros recebidos: nome=banana, preco=3.0, quantidade_estoque=10, categoria_id=2
2025-03-20 11:26:13,080 | INFO | ProdutoService | Produto criado: banana, Preço: 3.0, Estoque: 10
2025-03-20 11:26:13,080 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:26:14,079 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:26:14,079 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:26:14,383 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:26:14,383 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:26:14,387 | INFO | produto_routes | Listando produtos ativos.
2025-03-20 11:26:14,389 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:28:56,735 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 11:28:56,908 | DEBUG | app | API carregando banco: sqlite:///:memory:
2025-03-20 11:28:56,976 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 11:28:58,063 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:28:58,063 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:28:58,385 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:28:58,387 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:28:59,403 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:28:59,404 | INFO | routes.api.auth | Dados recebidos: {'email': 'user@email.com', 'password': '123456'}
2025-03-20 11:28:59,743 | INFO | ProdutoService | Utilizador user@email.com autenticado.
2025-03-20 11:28:59,744 | INFO | routes.api.auth | Utilizador autenticado: user@email.com
2025-03-20 11:29:00,749 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:29:00,750 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'teste errado'}
2025-03-20 11:29:01,115 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-20 11:29:01,116 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-20 11:29:02,328 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:29:02,328 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:29:02,706 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:29:02,708 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:29:02,716 | INFO | routes.api.auth | Logout com sucesso
2025-03-20 11:29:03,682 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:29:03,682 | INFO | routes.api.auth | Dados recebidos: {}
2025-03-20 11:29:03,685 | WARNING | routes.api.auth | Tentativa de login sem credenciais fornecidas.
2025-03-20 11:29:04,644 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:29:04,644 | INFO | routes.api.auth | Dados recebidos: {'email': 'naoexiste@email.com', 'password': '123456'}
2025-03-20 11:29:04,646 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: naoexiste@email.com
2025-03-20 11:29:04,646 | WARNING | routes.api.auth | Falha na autenticação para o email: naoexiste@email.com
2025-03-20 11:29:05,643 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:29:05,645 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'senhaerrada'}
2025-03-20 11:29:06,002 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-20 11:29:06,002 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-20 11:29:07,063 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:29:07,063 | INFO | routes.api.auth | Dados recebidos: {'email': 'email-invalido', 'password': '123456'}
2025-03-20 11:29:07,063 | WARNING | routes.api.auth | Tenativa de login de email envalido.
2025-03-20 11:29:09,042 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:29:09,042 | INFO | routes.api.auth | Formato de envio incorreto, não foi JSON
2025-03-20 11:29:13,172 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:29:13,172 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:29:13,498 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:29:13,498 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:29:13,503 | INFO | routes.api.auth | Logout com sucesso
2025-03-20 11:29:14,488 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:29:14,488 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:29:14,825 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:29:14,826 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:29:14,836 | INFO | CategoriaService | Categoria criada: Fruta
2025-03-20 11:29:14,836 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:29:14,838 | INFO | routes.api.categorias | Nova categoria criada Fruta
2025-03-20 11:29:15,836 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:29:15,836 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:29:16,164 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:29:16,164 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:29:16,171 | INFO | CategoriaService | Categoria criada: Categoria Teste
2025-03-20 11:29:16,171 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:29:16,171 | INFO | routes.api.categorias | Nova categoria criada Categoria Teste
2025-03-20 11:29:16,174 | INFO | ProdutoService | Parâmetros recebidos: nome=banana, preco=3.0, quantidade_estoque=10, categoria_id=2
2025-03-20 11:29:16,181 | INFO | ProdutoService | Produto criado: banana, Preço: 3.0, Estoque: 10
2025-03-20 11:29:16,181 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:29:17,206 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:29:17,206 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:29:17,548 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:29:17,548 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:29:17,552 | INFO | produto_routes | Listando produtos ativos.
2025-03-20 11:29:17,558 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:31:30,935 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 11:31:31,100 | DEBUG | app | API carregando banco: sqlite:///:memory:
2025-03-20 11:31:31,173 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 11:31:32,162 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:31:32,162 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:31:32,462 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:31:32,463 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:31:33,448 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:31:33,448 | INFO | routes.api.auth | Dados recebidos: {'email': 'user@email.com', 'password': '123456'}
2025-03-20 11:31:33,766 | INFO | ProdutoService | Utilizador user@email.com autenticado.
2025-03-20 11:31:33,766 | INFO | routes.api.auth | Utilizador autenticado: user@email.com
2025-03-20 11:31:34,734 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:31:34,734 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'teste errado'}
2025-03-20 11:31:35,066 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-20 11:31:35,066 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-20 11:31:36,130 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:31:36,130 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:31:36,441 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:31:36,442 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:31:36,449 | INFO | routes.api.auth | Logout com sucesso
2025-03-20 11:31:37,419 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:31:37,419 | INFO | routes.api.auth | Dados recebidos: {}
2025-03-20 11:31:37,419 | WARNING | routes.api.auth | Tentativa de login sem credenciais fornecidas.
2025-03-20 11:31:38,351 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:31:38,369 | INFO | routes.api.auth | Dados recebidos: {'email': 'naoexiste@email.com', 'password': '123456'}
2025-03-20 11:31:38,370 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: naoexiste@email.com
2025-03-20 11:31:38,370 | WARNING | routes.api.auth | Falha na autenticação para o email: naoexiste@email.com
2025-03-20 11:31:39,343 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:31:39,343 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'senhaerrada'}
2025-03-20 11:31:39,647 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-20 11:31:39,649 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-20 11:31:40,595 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:31:40,595 | INFO | routes.api.auth | Dados recebidos: {'email': 'email-invalido', 'password': '123456'}
2025-03-20 11:31:40,595 | WARNING | routes.api.auth | Tenativa de login de email envalido.
2025-03-20 11:31:42,485 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:31:42,485 | INFO | routes.api.auth | Formato de envio incorreto, não foi JSON
2025-03-20 11:31:46,386 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:31:46,387 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:31:46,689 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:31:46,690 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:31:46,693 | INFO | routes.api.auth | Logout com sucesso
2025-03-20 11:31:47,640 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:31:47,640 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:31:47,956 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:31:47,956 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:31:47,965 | INFO | CategoriaService | Categoria criada: Fruta
2025-03-20 11:31:47,965 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:31:47,965 | INFO | routes.api.categorias | Nova categoria criada Fruta
2025-03-20 11:31:48,899 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:31:48,899 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:31:49,199 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:31:49,200 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:31:49,206 | INFO | CategoriaService | Categoria criada: Categoria Teste
2025-03-20 11:31:49,269 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:31:49,269 | INFO | routes.api.categorias | Nova categoria criada Categoria Teste
2025-03-20 11:31:49,271 | INFO | ProdutoService | Parâmetros recebidos: nome=banana, preco=3.0, quantidade_estoque=10, categoria_id=2
2025-03-20 11:31:49,279 | INFO | ProdutoService | Produto criado: banana, Preço: 3.0, Estoque: 10
2025-03-20 11:31:49,280 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:31:50,224 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:31:50,224 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:31:50,567 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:31:50,568 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:31:50,570 | INFO | produto_routes | Listando produtos ativos.
2025-03-20 11:31:50,575 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:51:37,183 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 11:51:37,388 | DEBUG | app | API carregando banco: sqlite:///:memory:
2025-03-20 11:51:37,460 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 11:51:38,453 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:51:38,454 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:51:38,779 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:51:38,781 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:51:39,930 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:51:39,931 | INFO | routes.api.auth | Dados recebidos: {'email': 'user@email.com', 'password': '123456'}
2025-03-20 11:51:40,262 | INFO | ProdutoService | Utilizador user@email.com autenticado.
2025-03-20 11:51:40,263 | INFO | routes.api.auth | Utilizador autenticado: user@email.com
2025-03-20 11:51:41,364 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:51:41,364 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'teste errado'}
2025-03-20 11:51:41,757 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-20 11:51:41,758 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-20 11:51:42,772 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:51:42,773 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:51:43,100 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:51:43,101 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:51:43,107 | INFO | routes.api.auth | Logout com sucesso
2025-03-20 11:51:44,118 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:51:44,119 | INFO | routes.api.auth | Dados recebidos: {}
2025-03-20 11:51:44,119 | WARNING | routes.api.auth | Tentativa de login sem credenciais fornecidas.
2025-03-20 11:51:45,147 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:51:45,147 | INFO | routes.api.auth | Dados recebidos: {'email': 'naoexiste@email.com', 'password': '123456'}
2025-03-20 11:51:45,147 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: naoexiste@email.com
2025-03-20 11:51:45,150 | WARNING | routes.api.auth | Falha na autenticação para o email: naoexiste@email.com
2025-03-20 11:51:46,163 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:51:46,163 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'senhaerrada'}
2025-03-20 11:51:46,489 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-20 11:51:46,489 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-20 11:51:47,544 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:51:47,544 | INFO | routes.api.auth | Dados recebidos: {'email': 'email-invalido', 'password': '123456'}
2025-03-20 11:51:47,544 | WARNING | routes.api.auth | Tenativa de login de email envalido.
2025-03-20 11:51:49,603 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:51:49,603 | INFO | routes.api.auth | Formato de envio incorreto, não foi JSON
2025-03-20 11:51:53,723 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:51:53,723 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:51:54,123 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:51:54,124 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:51:54,130 | INFO | routes.api.auth | Logout com sucesso
2025-03-20 11:51:55,114 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:51:55,115 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:51:55,447 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:51:55,449 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:51:55,461 | INFO | CategoriaService | Categoria criada: Fruta
2025-03-20 11:51:55,461 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:51:55,462 | INFO | routes.api.categorias | Nova categoria criada Fruta
2025-03-20 11:51:56,456 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:51:56,457 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:51:56,792 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:51:56,794 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:51:56,802 | INFO | CategoriaService | Categoria criada: Categoria Teste
2025-03-20 11:51:56,802 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:51:56,803 | INFO | routes.api.categorias | Nova categoria criada Categoria Teste
2025-03-20 11:51:56,805 | INFO | ProdutoService | Parâmetros recebidos: nome=banana, preco=3.0, quantidade_estoque=10, categoria_id=2
2025-03-20 11:51:56,815 | INFO | ProdutoService | Produto criado: banana, Preço: 3.0, Estoque: 10
2025-03-20 11:51:56,817 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:51:56,817 | INFO | routes.api.produtos | Produto criado com sucesso: {'id': 1, 'nome': 'banana', 'descricao': None, 'preco': 3.0, 'quantidade_estoque': 10, 'ativo': True, 'categoria_id': 2, 'criado_em': datetime.datetime(2025, 3, 20, 11, 51, 56, 811956), 'atualizado_em': datetime.datetime(2025, 3, 20, 11, 51, 56, 811956)}
2025-03-20 11:51:57,841 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:51:57,841 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:51:58,185 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:51:58,185 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:51:58,188 | INFO | routes.api.produtos | Listando produtos ativos.
2025-03-20 11:51:58,195 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:56:10,624 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 11:56:10,902 | DEBUG | app | API carregando banco: sqlite:///:memory:
2025-03-20 11:56:10,964 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 11:56:11,920 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:56:11,976 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:56:12,342 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:56:12,343 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:56:12,353 | INFO | routes.api.auth | Logout com sucesso
2025-03-20 11:56:19,699 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 11:56:19,888 | DEBUG | app | API carregando banco: sqlite:///:memory:
2025-03-20 11:56:19,954 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 11:56:20,993 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:56:20,995 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:56:21,342 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:56:21,344 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:56:22,289 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:56:22,289 | INFO | routes.api.auth | Dados recebidos: {'email': 'user@email.com', 'password': '123456'}
2025-03-20 11:56:22,678 | INFO | ProdutoService | Utilizador user@email.com autenticado.
2025-03-20 11:56:22,679 | INFO | routes.api.auth | Utilizador autenticado: user@email.com
2025-03-20 11:56:23,620 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:56:23,621 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'teste errado'}
2025-03-20 11:56:23,972 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-20 11:56:23,972 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-20 11:56:24,946 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:56:24,947 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:56:25,267 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:56:25,269 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:56:25,275 | INFO | routes.api.auth | Logout com sucesso
2025-03-20 11:56:26,229 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:56:26,230 | INFO | routes.api.auth | Dados recebidos: {}
2025-03-20 11:56:26,230 | WARNING | routes.api.auth | Tentativa de login sem credenciais fornecidas.
2025-03-20 11:56:27,264 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:56:27,265 | INFO | routes.api.auth | Dados recebidos: {'email': 'naoexiste@email.com', 'password': '123456'}
2025-03-20 11:56:27,266 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: naoexiste@email.com
2025-03-20 11:56:27,266 | WARNING | routes.api.auth | Falha na autenticação para o email: naoexiste@email.com
2025-03-20 11:56:28,349 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:56:28,349 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'senhaerrada'}
2025-03-20 11:56:28,822 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-20 11:56:28,822 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-20 11:56:29,790 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:56:29,791 | INFO | routes.api.auth | Dados recebidos: {'email': 'email-invalido', 'password': '123456'}
2025-03-20 11:56:29,791 | WARNING | routes.api.auth | Tenativa de login de email envalido.
2025-03-20 11:56:31,723 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:56:31,723 | INFO | routes.api.auth | Formato de envio incorreto, não foi JSON
2025-03-20 11:56:35,925 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:56:35,925 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:56:36,251 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:56:36,252 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:56:36,255 | INFO | routes.api.auth | Logout com sucesso
2025-03-20 11:56:37,232 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:56:37,232 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:56:37,554 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:56:37,555 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:57:55,020 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 11:57:55,164 | DEBUG | app | API carregando banco: sqlite:///:memory:
2025-03-20 11:57:55,242 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 11:57:56,280 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:57:56,281 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:57:56,611 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:57:56,612 | ERROR | routes.api.auth | Erro inesperado no login: 'Utilizador' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\routes\api\auth.py", line 51, in login
    access_token, refresh_token = AuthService.gerar_tokens(utilizador)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\services\authmanager.py", line 20, in gerar_tokens
    "id": utilizador["id"],
         ~~~~~~~~~~^^^^^^
TypeError: 'Utilizador' object is not subscriptable
2025-03-20 11:58:18,301 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 11:58:18,428 | DEBUG | app | API carregando banco: sqlite:///:memory:
2025-03-20 11:58:18,504 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 11:58:19,488 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:58:19,488 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:58:19,926 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:58:19,926 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:59:12,986 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 11:59:13,104 | DEBUG | app | API carregando banco: sqlite:///:memory:
2025-03-20 11:59:13,179 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 11:59:14,226 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 11:59:14,227 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:59:14,568 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:59:14,569 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 12:03:03,033 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 12:03:03,167 | DEBUG | app | API carregando banco: sqlite:///:memory:
2025-03-20 12:03:03,232 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 12:03:04,181 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 12:03:04,181 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 12:03:04,495 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 12:03:04,495 | ERROR | routes.api.auth | Erro inesperado no login: 'Utilizador' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\routes\api\auth.py", line 51, in login
    access_token, refresh_token = AuthService.gerar_tokens(utilizador)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\services\authmanager.py", line 20, in gerar_tokens
    "id": utilizador["id"],
         ~~~~~~~~~~^^^^^^
TypeError: 'Utilizador' object is not subscriptable
2025-03-20 12:04:11,099 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 12:04:11,225 | DEBUG | app | API carregando banco: sqlite:///:memory:
2025-03-20 12:04:11,305 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 12:04:12,316 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 12:04:12,316 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 12:04:12,643 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 12:04:12,644 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 12:09:19,638 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 12:09:19,838 | DEBUG | app | API carregando banco: sqlite:///:memory:
2025-03-20 12:09:19,907 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 12:09:20,871 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 12:09:20,871 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 12:09:21,190 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 12:09:21,190 | ERROR | routes.api.auth | Erro inesperado no login: 'Utilizador' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\routes\api\auth.py", line 51, in login
    access_token, refresh_token = AuthService.gerar_tokens(utilizador)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\services\authmanager.py", line 20, in gerar_tokens
    "id": utilizador["id"],
          ~~~~~~~~~~^^^^^^
TypeError: 'Utilizador' object is not subscriptable
2025-03-20 12:10:52,278 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 12:10:52,450 | DEBUG | app | API carregando banco: sqlite:///:memory:
2025-03-20 12:10:52,523 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 12:10:53,525 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 12:10:53,525 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 12:10:53,849 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 12:10:53,855 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 12:14:26,379 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 12:14:26,506 | DEBUG | app | API carregando banco: sqlite:///:memory:
2025-03-20 12:14:26,572 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 12:14:27,569 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 12:14:27,569 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 12:14:27,887 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 12:14:27,888 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 12:16:25,921 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 12:16:26,081 | DEBUG | app | API carregando banco: sqlite:///:memory:
2025-03-20 12:16:26,151 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 12:16:27,214 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 12:16:27,214 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 12:16:27,545 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 12:16:27,546 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 12:16:28,598 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 12:16:28,599 | INFO | routes.api.auth | Dados recebidos: {'email': 'user@email.com', 'password': '123456'}
2025-03-20 12:16:28,931 | INFO | ProdutoService | Utilizador user@email.com autenticado.
2025-03-20 12:16:28,933 | INFO | routes.api.auth | Utilizador autenticado: user@email.com
2025-03-20 12:16:29,890 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 12:16:29,891 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'teste errado'}
2025-03-20 12:16:30,219 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-20 12:16:30,220 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-20 12:16:31,201 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 12:16:31,201 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 12:16:31,531 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 12:16:31,531 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 12:16:31,540 | INFO | routes.api.auth | Logout com sucesso
2025-03-20 12:16:32,565 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 12:16:32,565 | INFO | routes.api.auth | Dados recebidos: {}
2025-03-20 12:16:32,565 | WARNING | routes.api.auth | Tentativa de login sem credenciais fornecidas.
2025-03-20 12:16:33,609 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 12:16:33,610 | INFO | routes.api.auth | Dados recebidos: {'email': 'naoexiste@email.com', 'password': '123456'}
2025-03-20 12:16:33,612 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: naoexiste@email.com
2025-03-20 12:16:33,612 | WARNING | routes.api.auth | Falha na autenticação para o email: naoexiste@email.com
2025-03-20 12:16:34,614 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 12:16:34,614 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'senhaerrada'}
2025-03-20 12:16:34,938 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-20 12:16:34,938 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-20 12:16:35,981 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 12:16:35,982 | INFO | routes.api.auth | Dados recebidos: {'email': 'email-invalido', 'password': '123456'}
2025-03-20 12:16:35,982 | WARNING | routes.api.auth | Tenativa de login de email envalido.
2025-03-20 12:16:38,011 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 12:16:38,011 | INFO | routes.api.auth | Formato de envio incorreto, não foi JSON
2025-03-20 12:16:42,278 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 12:16:42,278 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 12:16:42,615 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 12:16:42,616 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 12:16:42,619 | INFO | routes.api.auth | Logout com sucesso
2025-03-20 12:16:43,652 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 12:16:43,652 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 12:16:44,002 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 12:16:44,003 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 12:16:48,178 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 12:16:48,178 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 12:16:48,532 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 12:16:48,533 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 12:16:48,545 | INFO | CategoriaService | Categoria criada: Fruta
2025-03-20 12:16:48,546 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 12:16:48,546 | INFO | routes.api.categorias | Nova categoria criada Fruta
2025-03-20 12:16:49,663 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 12:16:49,663 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 12:16:50,021 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 12:16:50,022 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 12:16:50,031 | INFO | CategoriaService | Categoria criada: Categoria Teste
2025-03-20 12:16:50,032 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 12:16:50,032 | INFO | routes.api.categorias | Nova categoria criada Categoria Teste
2025-03-20 12:16:50,035 | INFO | ProdutoService | Parâmetros recebidos: nome=banana, preco=3.0, quantidade_estoque=10, categoria_id=2
2025-03-20 12:16:50,047 | INFO | ProdutoService | Produto criado: banana, Preço: 3.0, Estoque: 10
2025-03-20 12:16:50,048 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 12:16:50,048 | INFO | routes.api.produtos | Produto criado com sucesso: {'id': 1, 'nome': 'banana', 'descricao': None, 'preco': 3.0, 'quantidade_estoque': 10, 'ativo': True, 'categoria_id': 2, 'criado_em': datetime.datetime(2025, 3, 20, 12, 16, 50, 42963), 'atualizado_em': datetime.datetime(2025, 3, 20, 12, 16, 50, 42963)}
2025-03-20 12:16:51,148 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 12:16:51,149 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 12:16:51,535 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 12:16:51,536 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 12:16:51,540 | INFO | routes.api.produtos | Listando produtos ativos.
2025-03-20 12:16:51,545 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 20:50:01,856 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 20:50:01,958 | INFO | database | Resetando a instância do Database.
2025-03-20 20:50:01,961 | INFO | app | Inicializando a aplicação Flask.
2025-03-20 20:50:01,961 | DEBUG | app | Configurações carregadas: <Config {'DEBUG': True, 'TESTING': True, 'PROPAGATE_EXCEPTIONS': None, 'SECRET_KEY': 'chamafilho', 'SECRET_KEY_FALLBACKS': None, 'PERMANENT_SESSION_LIFETIME': datetime.timedelta(days=31), 'USE_X_SENDFILE': False, 'TRUSTED_HOSTS': None, 'SERVER_NAME': None, 'APPLICATION_ROOT': '/', 'SESSION_COOKIE_NAME': 'session', 'SESSION_COOKIE_DOMAIN': None, 'SESSION_COOKIE_PATH': None, 'SESSION_COOKIE_HTTPONLY': True, 'SESSION_COOKIE_SECURE': False, 'SESSION_COOKIE_PARTITIONED': False, 'SESSION_COOKIE_SAMESITE': None, 'SESSION_REFRESH_EACH_REQUEST': True, 'MAX_CONTENT_LENGTH': None, 'MAX_FORM_MEMORY_SIZE': 500000, 'MAX_FORM_PARTS': 1000, 'SEND_FILE_MAX_AGE_DEFAULT': None, 'TRAP_BAD_REQUEST_ERRORS': None, 'TRAP_HTTP_EXCEPTIONS': False, 'EXPLAIN_TEMPLATE_LOADING': False, 'PREFERRED_URL_SCHEME': 'http', 'TEMPLATES_AUTO_RELOAD': None, 'MAX_COOKIE_SIZE': 4093, 'PROVIDE_AUTOMATIC_OPTIONS': True, 'BASE_DIR': 'C:\\Users\\tutas\\Documents\\Projetos GitHUB\\store-management-system', 'SQLALCHEMY_DATABASE_URI': 'sqlite:///:memory:', 'SQLALCHEMY_TRACK_MODIFICATIONS': False}>
2025-03-20 20:50:01,961 | INFO | database | Criando nova instância do Database.
2025-03-20 20:50:01,961 | INFO | database | Usando o banco de dados: sqlite:///:memory:
2025-03-20 20:50:02,002 | INFO | database | Registrando modelos e criando tabelas, se necessário.
2025-03-20 20:50:02,018 | INFO | app | Banco de dados configurado e modelos registrados com sucesso.
2025-03-20 20:50:02,034 | INFO | app | Rotas inicializadas com sucesso.
2025-03-20 20:50:02,034 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:50:02,034 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:50:02,035 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 20:50:02,036 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:50:02,036 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:50:02,492 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 20:50:02,492 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 20:50:02,494 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:50:02,494 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:50:02,626 | INFO | services.utilizadoresmanager | Utilizador admin@email.com autenticado.
2025-03-20 20:50:02,627 | INFO | services.authmanager | Token gerado com sucesso.
2025-03-20 20:50:02,627 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 20:50:02,631 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:50:02,631 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:50:03,019 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 20:50:03,019 | INFO | routes.api.auth | Dados recebidos: {'email': 'user@email.com', 'password': '123456'}
2025-03-20 20:50:03,019 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:50:03,019 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:50:03,148 | INFO | services.utilizadoresmanager | Utilizador user@email.com autenticado.
2025-03-20 20:50:03,149 | INFO | services.authmanager | Token gerado com sucesso.
2025-03-20 20:50:03,149 | INFO | routes.api.auth | Utilizador autenticado: user@email.com
2025-03-20 20:50:03,152 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:50:03,152 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:50:03,544 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 20:50:03,544 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'teste errado'}
2025-03-20 20:50:03,544 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:50:03,544 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:50:03,673 | INFO | services.utilizadoresmanager | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-20 20:50:03,673 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-20 20:50:03,676 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:50:03,676 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:50:04,064 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 20:50:04,064 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 20:50:04,064 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:50:04,064 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:50:04,193 | INFO | services.utilizadoresmanager | Utilizador admin@email.com autenticado.
2025-03-20 20:50:04,193 | INFO | services.authmanager | Token gerado com sucesso.
2025-03-20 20:50:04,194 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 20:50:04,195 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:50:04,195 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:50:04,196 | DEBUG | services.authmanager | Token validado com sucesso.
2025-03-20 20:50:04,196 | INFO | services.tokenrevogadomanager | Token revogado: <models.tokenrevogado.TokenRevogado object at 0x0000021B7CABE210>
2025-03-20 20:50:04,197 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:50:04,197 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:50:04,198 | INFO | routes.api.auth | Logout com sucesso
2025-03-20 20:50:04,200 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:50:04,200 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:50:04,586 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 20:50:04,586 | INFO | routes.api.auth | Dados recebidos: {}
2025-03-20 20:50:04,586 | WARNING | routes.api.auth | Tentativa de login sem credenciais fornecidas.
2025-03-20 20:50:04,589 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:50:04,589 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:50:04,976 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 20:50:04,976 | INFO | routes.api.auth | Dados recebidos: {'email': 'naoexiste@email.com', 'password': '123456'}
2025-03-20 20:50:04,976 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:50:04,976 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:50:04,977 | INFO | services.utilizadoresmanager | Token não gerado, dados não autenticados, email: naoexiste@email.com
2025-03-20 20:50:04,977 | WARNING | routes.api.auth | Falha na autenticação para o email: naoexiste@email.com
2025-03-20 20:50:04,980 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:50:04,980 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:50:05,365 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 20:50:05,365 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'senhaerrada'}
2025-03-20 20:50:05,365 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:50:05,365 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:50:05,493 | INFO | services.utilizadoresmanager | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-20 20:50:05,493 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-20 20:50:05,496 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:50:05,496 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:50:05,885 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 20:50:05,885 | INFO | routes.api.auth | Dados recebidos: {'email': 'email-invalido', 'password': '123456'}
2025-03-20 20:50:05,885 | WARNING | routes.api.auth | Tenativa de login de email envalido.
2025-03-20 20:50:05,888 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:50:05,888 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:50:06,280 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:50:06,280 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:50:06,666 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 20:50:06,666 | INFO | routes.api.auth | Formato de envio incorreto, não foi JSON
2025-03-20 20:50:06,669 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:50:06,669 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:50:07,058 | WARNING | services.authmanager | Tentativa de validar token expirado
2025-03-20 20:50:07,061 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:50:07,061 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:50:07,447 | WARNING | services.authmanager | Tentativa de válidar token inválido.
2025-03-20 20:50:07,450 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:50:07,450 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:50:07,840 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:50:07,840 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:50:08,235 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 20:50:08,235 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 20:50:08,235 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:50:08,235 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:50:08,365 | INFO | services.utilizadoresmanager | Utilizador admin@email.com autenticado.
2025-03-20 20:50:08,366 | INFO | services.authmanager | Token gerado com sucesso.
2025-03-20 20:50:08,366 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 20:50:08,367 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:50:08,367 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:50:08,367 | DEBUG | services.authmanager | Token validado com sucesso.
2025-03-20 20:50:08,367 | INFO | services.tokenrevogadomanager | Token revogado: <models.tokenrevogado.TokenRevogado object at 0x0000021B7CBDA000>
2025-03-20 20:50:08,368 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:50:08,368 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:50:08,368 | INFO | routes.api.auth | Logout com sucesso
2025-03-20 20:50:08,369 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:50:08,369 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:50:08,373 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:50:08,373 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:50:08,765 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 20:50:08,765 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 20:50:08,765 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:50:08,765 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:50:08,894 | INFO | services.utilizadoresmanager | Utilizador admin@email.com autenticado.
2025-03-20 20:50:08,895 | INFO | services.authmanager | Token gerado com sucesso.
2025-03-20 20:50:08,895 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 20:50:08,896 | INFO | services.authmanager | Token gerado com sucesso.
2025-03-20 20:50:08,899 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:50:08,899 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:50:09,289 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:50:09,289 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:50:09,677 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:50:09,678 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:50:10,067 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:50:10,068 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:50:10,455 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 20:50:10,455 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 20:50:10,456 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:50:10,456 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:50:10,586 | INFO | services.utilizadoresmanager | Utilizador admin@email.com autenticado.
2025-03-20 20:50:10,587 | INFO | services.authmanager | Token gerado com sucesso.
2025-03-20 20:50:10,587 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 20:50:10,587 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:50:10,588 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:50:10,588 | DEBUG | services.authmanager | Token validado com sucesso.
2025-03-20 20:50:10,793 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:50:10,793 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:50:11,179 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 20:50:11,179 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 20:50:11,179 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:50:11,179 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:50:11,306 | INFO | services.utilizadoresmanager | Utilizador admin@email.com autenticado.
2025-03-20 20:50:11,307 | INFO | services.authmanager | Token gerado com sucesso.
2025-03-20 20:50:11,307 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 20:50:11,307 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:50:11,308 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:50:11,308 | DEBUG | services.authmanager | Token validado com sucesso.
2025-03-20 20:50:11,386 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:50:11,386 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:50:11,776 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 20:50:11,777 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 20:50:11,777 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:50:11,777 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:50:11,906 | INFO | services.utilizadoresmanager | Utilizador admin@email.com autenticado.
2025-03-20 20:50:11,906 | INFO | services.authmanager | Token gerado com sucesso.
2025-03-20 20:50:11,906 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 20:50:11,907 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:50:11,907 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:50:11,908 | DEBUG | services.authmanager | Token validado com sucesso.
2025-03-20 20:51:03,439 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 20:51:40,913 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 20:51:40,969 | INFO | database | Resetando a instância do Database.
2025-03-20 20:51:40,971 | INFO | app | Inicializando a aplicação Flask.
2025-03-20 20:51:40,971 | DEBUG | app | Configurações carregadas: <Config {'DEBUG': True, 'TESTING': True, 'PROPAGATE_EXCEPTIONS': None, 'SECRET_KEY': 'chamafilho', 'SECRET_KEY_FALLBACKS': None, 'PERMANENT_SESSION_LIFETIME': datetime.timedelta(days=31), 'USE_X_SENDFILE': False, 'TRUSTED_HOSTS': None, 'SERVER_NAME': None, 'APPLICATION_ROOT': '/', 'SESSION_COOKIE_NAME': 'session', 'SESSION_COOKIE_DOMAIN': None, 'SESSION_COOKIE_PATH': None, 'SESSION_COOKIE_HTTPONLY': True, 'SESSION_COOKIE_SECURE': False, 'SESSION_COOKIE_PARTITIONED': False, 'SESSION_COOKIE_SAMESITE': None, 'SESSION_REFRESH_EACH_REQUEST': True, 'MAX_CONTENT_LENGTH': None, 'MAX_FORM_MEMORY_SIZE': 500000, 'MAX_FORM_PARTS': 1000, 'SEND_FILE_MAX_AGE_DEFAULT': None, 'TRAP_BAD_REQUEST_ERRORS': None, 'TRAP_HTTP_EXCEPTIONS': False, 'EXPLAIN_TEMPLATE_LOADING': False, 'PREFERRED_URL_SCHEME': 'http', 'TEMPLATES_AUTO_RELOAD': None, 'MAX_COOKIE_SIZE': 4093, 'PROVIDE_AUTOMATIC_OPTIONS': True, 'BASE_DIR': 'C:\\Users\\tutas\\Documents\\Projetos GitHUB\\store-management-system', 'SQLALCHEMY_DATABASE_URI': 'sqlite:///:memory:', 'SQLALCHEMY_TRACK_MODIFICATIONS': False}>
2025-03-20 20:51:40,971 | INFO | database | Criando nova instância do Database.
2025-03-20 20:51:40,971 | INFO | database | Usando o banco de dados: sqlite:///:memory:
2025-03-20 20:51:40,986 | INFO | database | Registrando modelos e criando tabelas, se necessário.
2025-03-20 20:51:40,990 | INFO | app | Banco de dados configurado e modelos registrados com sucesso.
2025-03-20 20:51:40,996 | INFO | app | Rotas inicializadas com sucesso.
2025-03-20 20:51:40,996 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:51:40,997 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:51:40,997 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 20:51:40,998 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:51:40,998 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:51:41,413 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 20:51:41,413 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 20:51:41,414 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:51:41,414 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:51:41,544 | INFO | services.utilizadoresmanager | Utilizador admin@email.com autenticado.
2025-03-20 20:51:41,545 | INFO | services.authmanager | Token gerado com sucesso.
2025-03-20 20:51:41,545 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 20:51:41,546 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:51:41,546 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:51:41,547 | DEBUG | services.authmanager | Token validado com sucesso.
2025-03-20 20:51:46,271 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 20:51:46,322 | INFO | database | Resetando a instância do Database.
2025-03-20 20:51:46,323 | INFO | app | Inicializando a aplicação Flask.
2025-03-20 20:51:46,323 | DEBUG | app | Configurações carregadas: <Config {'DEBUG': True, 'TESTING': True, 'PROPAGATE_EXCEPTIONS': None, 'SECRET_KEY': 'chamafilho', 'SECRET_KEY_FALLBACKS': None, 'PERMANENT_SESSION_LIFETIME': datetime.timedelta(days=31), 'USE_X_SENDFILE': False, 'TRUSTED_HOSTS': None, 'SERVER_NAME': None, 'APPLICATION_ROOT': '/', 'SESSION_COOKIE_NAME': 'session', 'SESSION_COOKIE_DOMAIN': None, 'SESSION_COOKIE_PATH': None, 'SESSION_COOKIE_HTTPONLY': True, 'SESSION_COOKIE_SECURE': False, 'SESSION_COOKIE_PARTITIONED': False, 'SESSION_COOKIE_SAMESITE': None, 'SESSION_REFRESH_EACH_REQUEST': True, 'MAX_CONTENT_LENGTH': None, 'MAX_FORM_MEMORY_SIZE': 500000, 'MAX_FORM_PARTS': 1000, 'SEND_FILE_MAX_AGE_DEFAULT': None, 'TRAP_BAD_REQUEST_ERRORS': None, 'TRAP_HTTP_EXCEPTIONS': False, 'EXPLAIN_TEMPLATE_LOADING': False, 'PREFERRED_URL_SCHEME': 'http', 'TEMPLATES_AUTO_RELOAD': None, 'MAX_COOKIE_SIZE': 4093, 'PROVIDE_AUTOMATIC_OPTIONS': True, 'BASE_DIR': 'C:\\Users\\tutas\\Documents\\Projetos GitHUB\\store-management-system', 'SQLALCHEMY_DATABASE_URI': 'sqlite:///:memory:', 'SQLALCHEMY_TRACK_MODIFICATIONS': False}>
2025-03-20 20:51:46,323 | INFO | database | Criando nova instância do Database.
2025-03-20 20:51:46,323 | INFO | database | Usando o banco de dados: sqlite:///:memory:
2025-03-20 20:51:46,339 | INFO | database | Registrando modelos e criando tabelas, se necessário.
2025-03-20 20:51:46,343 | INFO | app | Banco de dados configurado e modelos registrados com sucesso.
2025-03-20 20:51:46,350 | INFO | app | Rotas inicializadas com sucesso.
2025-03-20 20:51:46,350 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:51:46,350 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:51:46,351 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 20:51:46,351 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:51:46,351 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:51:46,785 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 20:51:46,785 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 20:51:46,786 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:51:46,786 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:51:46,925 | INFO | services.utilizadoresmanager | Utilizador admin@email.com autenticado.
2025-03-20 20:51:46,926 | INFO | services.authmanager | Token gerado com sucesso.
2025-03-20 20:51:46,926 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 20:51:46,927 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:51:46,927 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:51:46,929 | DEBUG | services.authmanager | Token validado com sucesso.
2025-03-20 20:53:36,854 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 20:53:36,907 | INFO | database | Resetando a instância do Database.
2025-03-20 20:53:36,908 | INFO | app | Inicializando a aplicação Flask.
2025-03-20 20:53:36,909 | DEBUG | app | Configurações carregadas: <Config {'DEBUG': True, 'TESTING': True, 'PROPAGATE_EXCEPTIONS': None, 'SECRET_KEY': 'chamafilho', 'SECRET_KEY_FALLBACKS': None, 'PERMANENT_SESSION_LIFETIME': datetime.timedelta(days=31), 'USE_X_SENDFILE': False, 'TRUSTED_HOSTS': None, 'SERVER_NAME': None, 'APPLICATION_ROOT': '/', 'SESSION_COOKIE_NAME': 'session', 'SESSION_COOKIE_DOMAIN': None, 'SESSION_COOKIE_PATH': None, 'SESSION_COOKIE_HTTPONLY': True, 'SESSION_COOKIE_SECURE': False, 'SESSION_COOKIE_PARTITIONED': False, 'SESSION_COOKIE_SAMESITE': None, 'SESSION_REFRESH_EACH_REQUEST': True, 'MAX_CONTENT_LENGTH': None, 'MAX_FORM_MEMORY_SIZE': 500000, 'MAX_FORM_PARTS': 1000, 'SEND_FILE_MAX_AGE_DEFAULT': None, 'TRAP_BAD_REQUEST_ERRORS': None, 'TRAP_HTTP_EXCEPTIONS': False, 'EXPLAIN_TEMPLATE_LOADING': False, 'PREFERRED_URL_SCHEME': 'http', 'TEMPLATES_AUTO_RELOAD': None, 'MAX_COOKIE_SIZE': 4093, 'PROVIDE_AUTOMATIC_OPTIONS': True, 'BASE_DIR': 'C:\\Users\\tutas\\Documents\\Projetos GitHUB\\store-management-system', 'SQLALCHEMY_DATABASE_URI': 'sqlite:///:memory:', 'SQLALCHEMY_TRACK_MODIFICATIONS': False}>
2025-03-20 20:53:36,909 | INFO | database | Criando nova instância do Database.
2025-03-20 20:53:36,910 | INFO | database | Usando o banco de dados: sqlite:///:memory:
2025-03-20 20:53:36,935 | INFO | database | Registrando modelos e criando tabelas, se necessário.
2025-03-20 20:53:36,939 | INFO | app | Banco de dados configurado e modelos registrados com sucesso.
2025-03-20 20:53:36,949 | INFO | app | Rotas inicializadas com sucesso.
2025-03-20 20:53:36,950 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:53:36,950 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:53:36,950 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 20:53:36,951 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:53:36,951 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:53:37,378 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 20:53:37,378 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 20:53:37,379 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:53:37,379 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:53:37,517 | INFO | services.utilizadoresmanager | Utilizador admin@email.com autenticado.
2025-03-20 20:53:37,517 | INFO | services.authmanager | Token gerado com sucesso.
2025-03-20 20:53:37,517 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 20:53:37,518 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:53:37,518 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:53:37,520 | DEBUG | services.authmanager | Token validado com sucesso.
2025-03-20 20:53:37,520 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:53:37,520 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:53:37,523 | INFO | services.categoriamanager | Categoria criada: Fruta
2025-03-20 20:53:37,523 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 20:53:37,523 | INFO | routes.api.categorias | Nova categoria criada Fruta
2025-03-20 20:55:12,997 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 20:55:13,050 | INFO | database | Resetando a instância do Database.
2025-03-20 20:55:13,051 | INFO | app | Inicializando a aplicação Flask.
2025-03-20 20:55:13,051 | DEBUG | app | Configurações carregadas: <Config {'DEBUG': True, 'TESTING': True, 'PROPAGATE_EXCEPTIONS': None, 'SECRET_KEY': 'chamafilho', 'SECRET_KEY_FALLBACKS': None, 'PERMANENT_SESSION_LIFETIME': datetime.timedelta(days=31), 'USE_X_SENDFILE': False, 'TRUSTED_HOSTS': None, 'SERVER_NAME': None, 'APPLICATION_ROOT': '/', 'SESSION_COOKIE_NAME': 'session', 'SESSION_COOKIE_DOMAIN': None, 'SESSION_COOKIE_PATH': None, 'SESSION_COOKIE_HTTPONLY': True, 'SESSION_COOKIE_SECURE': False, 'SESSION_COOKIE_PARTITIONED': False, 'SESSION_COOKIE_SAMESITE': None, 'SESSION_REFRESH_EACH_REQUEST': True, 'MAX_CONTENT_LENGTH': None, 'MAX_FORM_MEMORY_SIZE': 500000, 'MAX_FORM_PARTS': 1000, 'SEND_FILE_MAX_AGE_DEFAULT': None, 'TRAP_BAD_REQUEST_ERRORS': None, 'TRAP_HTTP_EXCEPTIONS': False, 'EXPLAIN_TEMPLATE_LOADING': False, 'PREFERRED_URL_SCHEME': 'http', 'TEMPLATES_AUTO_RELOAD': None, 'MAX_COOKIE_SIZE': 4093, 'PROVIDE_AUTOMATIC_OPTIONS': True, 'BASE_DIR': 'C:\\Users\\tutas\\Documents\\Projetos GitHUB\\store-management-system', 'SQLALCHEMY_DATABASE_URI': 'sqlite:///:memory:', 'SQLALCHEMY_TRACK_MODIFICATIONS': False}>
2025-03-20 20:55:13,051 | INFO | database | Criando nova instância do Database.
2025-03-20 20:55:13,051 | INFO | database | Usando o banco de dados: sqlite:///:memory:
2025-03-20 20:55:13,066 | INFO | database | Registrando modelos e criando tabelas, se necessário.
2025-03-20 20:55:13,069 | INFO | app | Banco de dados configurado e modelos registrados com sucesso.
2025-03-20 20:55:13,077 | INFO | app | Rotas inicializadas com sucesso.
2025-03-20 20:55:13,077 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:55:13,077 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:55:13,077 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 20:55:13,078 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:55:13,078 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:55:13,484 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 20:55:13,484 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 20:55:13,484 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:55:13,484 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:55:13,617 | INFO | services.utilizadoresmanager | Utilizador admin@email.com autenticado.
2025-03-20 20:55:13,617 | INFO | services.authmanager | Token gerado com sucesso.
2025-03-20 20:55:13,617 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 20:55:13,618 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:55:13,619 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:55:13,620 | DEBUG | services.authmanager | Token validado com sucesso.
2025-03-20 20:57:02,984 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 20:57:03,036 | INFO | database | Resetando a instância do Database.
2025-03-20 20:57:03,037 | INFO | app | Inicializando a aplicação Flask.
2025-03-20 20:57:03,038 | DEBUG | app | Configurações carregadas: <Config {'DEBUG': True, 'TESTING': True, 'PROPAGATE_EXCEPTIONS': None, 'SECRET_KEY': 'chamafilho', 'SECRET_KEY_FALLBACKS': None, 'PERMANENT_SESSION_LIFETIME': datetime.timedelta(days=31), 'USE_X_SENDFILE': False, 'TRUSTED_HOSTS': None, 'SERVER_NAME': None, 'APPLICATION_ROOT': '/', 'SESSION_COOKIE_NAME': 'session', 'SESSION_COOKIE_DOMAIN': None, 'SESSION_COOKIE_PATH': None, 'SESSION_COOKIE_HTTPONLY': True, 'SESSION_COOKIE_SECURE': False, 'SESSION_COOKIE_PARTITIONED': False, 'SESSION_COOKIE_SAMESITE': None, 'SESSION_REFRESH_EACH_REQUEST': True, 'MAX_CONTENT_LENGTH': None, 'MAX_FORM_MEMORY_SIZE': 500000, 'MAX_FORM_PARTS': 1000, 'SEND_FILE_MAX_AGE_DEFAULT': None, 'TRAP_BAD_REQUEST_ERRORS': None, 'TRAP_HTTP_EXCEPTIONS': False, 'EXPLAIN_TEMPLATE_LOADING': False, 'PREFERRED_URL_SCHEME': 'http', 'TEMPLATES_AUTO_RELOAD': None, 'MAX_COOKIE_SIZE': 4093, 'PROVIDE_AUTOMATIC_OPTIONS': True, 'BASE_DIR': 'C:\\Users\\tutas\\Documents\\Projetos GitHUB\\store-management-system', 'SQLALCHEMY_DATABASE_URI': 'sqlite:///:memory:', 'SQLALCHEMY_TRACK_MODIFICATIONS': False}>
2025-03-20 20:57:03,038 | INFO | database | Criando nova instância do Database.
2025-03-20 20:57:03,038 | INFO | database | Usando o banco de dados: sqlite:///:memory:
2025-03-20 20:57:03,052 | INFO | database | Registrando modelos e criando tabelas, se necessário.
2025-03-20 20:57:03,057 | INFO | app | Banco de dados configurado e modelos registrados com sucesso.
2025-03-20 20:57:03,064 | INFO | app | Rotas inicializadas com sucesso.
2025-03-20 20:57:03,064 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:57:03,064 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:57:03,065 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 20:57:03,065 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:57:03,065 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:57:03,473 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 20:57:03,473 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 20:57:03,474 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:57:03,474 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:57:03,604 | INFO | services.utilizadoresmanager | Utilizador admin@email.com autenticado.
2025-03-20 20:57:03,605 | INFO | services.authmanager | Token gerado com sucesso.
2025-03-20 20:57:03,605 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 20:57:03,606 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:57:03,606 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:57:03,607 | DEBUG | services.authmanager | Token validado com sucesso.
2025-03-20 20:57:40,280 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 20:57:40,331 | INFO | database | Resetando a instância do Database.
2025-03-20 20:57:40,333 | INFO | app | Inicializando a aplicação Flask.
2025-03-20 20:57:40,333 | DEBUG | app | Configurações carregadas: <Config {'DEBUG': True, 'TESTING': True, 'PROPAGATE_EXCEPTIONS': None, 'SECRET_KEY': 'chamafilho', 'SECRET_KEY_FALLBACKS': None, 'PERMANENT_SESSION_LIFETIME': datetime.timedelta(days=31), 'USE_X_SENDFILE': False, 'TRUSTED_HOSTS': None, 'SERVER_NAME': None, 'APPLICATION_ROOT': '/', 'SESSION_COOKIE_NAME': 'session', 'SESSION_COOKIE_DOMAIN': None, 'SESSION_COOKIE_PATH': None, 'SESSION_COOKIE_HTTPONLY': True, 'SESSION_COOKIE_SECURE': False, 'SESSION_COOKIE_PARTITIONED': False, 'SESSION_COOKIE_SAMESITE': None, 'SESSION_REFRESH_EACH_REQUEST': True, 'MAX_CONTENT_LENGTH': None, 'MAX_FORM_MEMORY_SIZE': 500000, 'MAX_FORM_PARTS': 1000, 'SEND_FILE_MAX_AGE_DEFAULT': None, 'TRAP_BAD_REQUEST_ERRORS': None, 'TRAP_HTTP_EXCEPTIONS': False, 'EXPLAIN_TEMPLATE_LOADING': False, 'PREFERRED_URL_SCHEME': 'http', 'TEMPLATES_AUTO_RELOAD': None, 'MAX_COOKIE_SIZE': 4093, 'PROVIDE_AUTOMATIC_OPTIONS': True, 'BASE_DIR': 'C:\\Users\\tutas\\Documents\\Projetos GitHUB\\store-management-system', 'SQLALCHEMY_DATABASE_URI': 'sqlite:///:memory:', 'SQLALCHEMY_TRACK_MODIFICATIONS': False}>
2025-03-20 20:57:40,333 | INFO | database | Criando nova instância do Database.
2025-03-20 20:57:40,333 | INFO | database | Usando o banco de dados: sqlite:///:memory:
2025-03-20 20:57:40,348 | INFO | database | Registrando modelos e criando tabelas, se necessário.
2025-03-20 20:57:40,352 | INFO | app | Banco de dados configurado e modelos registrados com sucesso.
2025-03-20 20:57:40,359 | INFO | app | Rotas inicializadas com sucesso.
2025-03-20 20:57:40,359 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:57:40,359 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:57:40,360 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 20:57:40,360 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:57:40,360 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:57:40,781 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 20:57:40,782 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 20:57:40,782 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:57:40,782 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:57:40,921 | INFO | services.utilizadoresmanager | Utilizador admin@email.com autenticado.
2025-03-20 20:57:40,922 | INFO | services.authmanager | Token gerado com sucesso.
2025-03-20 20:57:40,922 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 20:57:40,923 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:57:40,923 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:57:40,924 | DEBUG | services.authmanager | Token validado com sucesso.
2025-03-20 20:57:40,925 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:57:40,925 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:57:40,928 | INFO | services.categoriamanager | Categoria criada: Fruta
2025-03-20 20:57:40,928 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 20:57:40,928 | INFO | routes.api.categorias | Nova categoria criada Fruta
2025-03-20 20:58:10,062 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 20:58:10,130 | INFO | database | Resetando a instância do Database.
2025-03-20 20:58:10,132 | INFO | app | Inicializando a aplicação Flask.
2025-03-20 20:58:10,132 | DEBUG | app | Configurações carregadas: <Config {'DEBUG': True, 'TESTING': True, 'PROPAGATE_EXCEPTIONS': None, 'SECRET_KEY': 'chamafilho', 'SECRET_KEY_FALLBACKS': None, 'PERMANENT_SESSION_LIFETIME': datetime.timedelta(days=31), 'USE_X_SENDFILE': False, 'TRUSTED_HOSTS': None, 'SERVER_NAME': None, 'APPLICATION_ROOT': '/', 'SESSION_COOKIE_NAME': 'session', 'SESSION_COOKIE_DOMAIN': None, 'SESSION_COOKIE_PATH': None, 'SESSION_COOKIE_HTTPONLY': True, 'SESSION_COOKIE_SECURE': False, 'SESSION_COOKIE_PARTITIONED': False, 'SESSION_COOKIE_SAMESITE': None, 'SESSION_REFRESH_EACH_REQUEST': True, 'MAX_CONTENT_LENGTH': None, 'MAX_FORM_MEMORY_SIZE': 500000, 'MAX_FORM_PARTS': 1000, 'SEND_FILE_MAX_AGE_DEFAULT': None, 'TRAP_BAD_REQUEST_ERRORS': None, 'TRAP_HTTP_EXCEPTIONS': False, 'EXPLAIN_TEMPLATE_LOADING': False, 'PREFERRED_URL_SCHEME': 'http', 'TEMPLATES_AUTO_RELOAD': None, 'MAX_COOKIE_SIZE': 4093, 'PROVIDE_AUTOMATIC_OPTIONS': True, 'BASE_DIR': 'C:\\Users\\tutas\\Documents\\Projetos GitHUB\\store-management-system', 'SQLALCHEMY_DATABASE_URI': 'sqlite:///:memory:', 'SQLALCHEMY_TRACK_MODIFICATIONS': False}>
2025-03-20 20:58:10,132 | INFO | database | Criando nova instância do Database.
2025-03-20 20:58:10,132 | INFO | database | Usando o banco de dados: sqlite:///:memory:
2025-03-20 20:58:10,147 | INFO | database | Registrando modelos e criando tabelas, se necessário.
2025-03-20 20:58:10,151 | INFO | app | Banco de dados configurado e modelos registrados com sucesso.
2025-03-20 20:58:10,160 | INFO | app | Rotas inicializadas com sucesso.
2025-03-20 20:58:10,160 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:10,160 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:10,161 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 20:58:10,161 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:10,161 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:10,569 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 20:58:10,569 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 20:58:10,569 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:10,569 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:10,700 | INFO | services.utilizadoresmanager | Utilizador admin@email.com autenticado.
2025-03-20 20:58:10,700 | INFO | services.authmanager | Token gerado com sucesso.
2025-03-20 20:58:10,700 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 20:58:10,704 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:10,704 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:11,104 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 20:58:11,104 | INFO | routes.api.auth | Dados recebidos: {'email': 'user@email.com', 'password': '123456'}
2025-03-20 20:58:11,105 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:11,105 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:11,235 | INFO | services.utilizadoresmanager | Utilizador user@email.com autenticado.
2025-03-20 20:58:11,236 | INFO | services.authmanager | Token gerado com sucesso.
2025-03-20 20:58:11,236 | INFO | routes.api.auth | Utilizador autenticado: user@email.com
2025-03-20 20:58:11,238 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:11,238 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:11,628 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 20:58:11,628 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'teste errado'}
2025-03-20 20:58:11,628 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:11,628 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:11,758 | INFO | services.utilizadoresmanager | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-20 20:58:11,759 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-20 20:58:11,761 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:11,761 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:12,170 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 20:58:12,170 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 20:58:12,171 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:12,171 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:12,303 | INFO | services.utilizadoresmanager | Utilizador admin@email.com autenticado.
2025-03-20 20:58:12,303 | INFO | services.authmanager | Token gerado com sucesso.
2025-03-20 20:58:12,303 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 20:58:12,304 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:12,304 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:12,306 | DEBUG | services.authmanager | Token validado com sucesso.
2025-03-20 20:58:12,306 | INFO | services.tokenrevogadomanager | Token revogado: <models.tokenrevogado.TokenRevogado object at 0x000001E41E00FA70>
2025-03-20 20:58:12,306 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:12,306 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:12,308 | INFO | routes.api.auth | Logout com sucesso
2025-03-20 20:58:12,312 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:12,312 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:12,705 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 20:58:12,705 | INFO | routes.api.auth | Dados recebidos: {}
2025-03-20 20:58:12,705 | WARNING | routes.api.auth | Tentativa de login sem credenciais fornecidas.
2025-03-20 20:58:12,708 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:12,708 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:13,100 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 20:58:13,100 | INFO | routes.api.auth | Dados recebidos: {'email': 'naoexiste@email.com', 'password': '123456'}
2025-03-20 20:58:13,100 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:13,100 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:13,101 | INFO | services.utilizadoresmanager | Token não gerado, dados não autenticados, email: naoexiste@email.com
2025-03-20 20:58:13,101 | WARNING | routes.api.auth | Falha na autenticação para o email: naoexiste@email.com
2025-03-20 20:58:13,103 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:13,103 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:13,494 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 20:58:13,495 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'senhaerrada'}
2025-03-20 20:58:13,495 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:13,495 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:13,638 | INFO | services.utilizadoresmanager | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-20 20:58:13,638 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-20 20:58:13,642 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:13,642 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:14,033 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 20:58:14,033 | INFO | routes.api.auth | Dados recebidos: {'email': 'email-invalido', 'password': '123456'}
2025-03-20 20:58:14,033 | WARNING | routes.api.auth | Tenativa de login de email envalido.
2025-03-20 20:58:14,036 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:14,036 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:14,427 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:14,427 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:14,815 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 20:58:14,815 | INFO | routes.api.auth | Formato de envio incorreto, não foi JSON
2025-03-20 20:58:14,818 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:14,818 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:15,231 | WARNING | services.authmanager | Tentativa de validar token expirado
2025-03-20 20:58:15,233 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:15,233 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:15,624 | WARNING | services.authmanager | Tentativa de válidar token inválido.
2025-03-20 20:58:15,628 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:15,628 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:16,025 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:16,025 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:16,422 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 20:58:16,422 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 20:58:16,422 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:16,422 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:16,563 | INFO | services.utilizadoresmanager | Utilizador admin@email.com autenticado.
2025-03-20 20:58:16,563 | INFO | services.authmanager | Token gerado com sucesso.
2025-03-20 20:58:16,563 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 20:58:16,563 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:16,564 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:16,564 | DEBUG | services.authmanager | Token validado com sucesso.
2025-03-20 20:58:16,565 | INFO | services.tokenrevogadomanager | Token revogado: <models.tokenrevogado.TokenRevogado object at 0x000001E41E155FA0>
2025-03-20 20:58:16,565 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:16,565 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:16,565 | INFO | routes.api.auth | Logout com sucesso
2025-03-20 20:58:16,566 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:16,566 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:16,570 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:16,570 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:16,962 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 20:58:16,962 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 20:58:16,962 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:16,962 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:17,091 | INFO | services.utilizadoresmanager | Utilizador admin@email.com autenticado.
2025-03-20 20:58:17,091 | INFO | services.authmanager | Token gerado com sucesso.
2025-03-20 20:58:17,091 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 20:58:17,092 | ERROR | services.authmanager | Tentativa de gerar token, erro: 'Utilizador' object has no attribute 'nome'
2025-03-20 20:58:17,305 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:17,305 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:17,716 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:17,717 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:18,109 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:18,109 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:18,507 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:18,507 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:18,897 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 20:58:18,898 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 20:58:18,898 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:18,898 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:19,025 | INFO | services.utilizadoresmanager | Utilizador admin@email.com autenticado.
2025-03-20 20:58:19,026 | INFO | services.authmanager | Token gerado com sucesso.
2025-03-20 20:58:19,026 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 20:58:19,027 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:19,027 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:19,027 | DEBUG | services.authmanager | Token validado com sucesso.
2025-03-20 20:58:19,028 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:19,028 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:19,031 | INFO | services.categoriamanager | Categoria criada: Fruta
2025-03-20 20:58:19,031 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 20:58:19,031 | INFO | routes.api.categorias | Nova categoria criada Fruta
2025-03-20 20:58:19,035 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:19,035 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:19,428 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 20:58:19,428 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 20:58:19,429 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:19,429 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:19,561 | INFO | services.utilizadoresmanager | Utilizador admin@email.com autenticado.
2025-03-20 20:58:19,561 | INFO | services.authmanager | Token gerado com sucesso.
2025-03-20 20:58:19,561 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 20:58:19,562 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:19,562 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:19,563 | DEBUG | services.authmanager | Token validado com sucesso.
2025-03-20 20:58:19,563 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:19,563 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:19,564 | INFO | services.categoriamanager | Categoria criada: Categoria Teste
2025-03-20 20:58:19,564 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 20:58:19,564 | INFO | routes.api.categorias | Nova categoria criada Categoria Teste
2025-03-20 20:58:19,565 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:19,565 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:19,565 | DEBUG | services.authmanager | Token validado com sucesso.
2025-03-20 20:58:19,565 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:19,566 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:19,566 | INFO | services.produtomanager | Parâmetros recebidos: nome=banana, preco=3.0, quantidade_estoque=10, categoria_id=2
2025-03-20 20:58:19,569 | INFO | services.produtomanager | Produto criado: banana, Preço: 3.0, Estoque: 10
2025-03-20 20:58:19,569 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 20:58:19,569 | INFO | routes.api.produtos | Produto criado com sucesso: {'id': 1, 'nome': 'banana', 'descricao': None, 'preco': 3.0, 'quantidade_estoque': 10, 'ativo': True, 'categoria_id': 2, 'criado_em': datetime.datetime(2025, 3, 20, 20, 58, 19, 568607), 'atualizado_em': datetime.datetime(2025, 3, 20, 20, 58, 19, 568607)}
2025-03-20 20:58:19,572 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:19,572 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:19,999 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 20:58:19,999 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 20:58:19,999 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:19,999 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:20,130 | INFO | services.utilizadoresmanager | Utilizador admin@email.com autenticado.
2025-03-20 20:58:20,131 | INFO | services.authmanager | Token gerado com sucesso.
2025-03-20 20:58:20,131 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 20:58:20,132 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:20,132 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:20,133 | DEBUG | services.authmanager | Token validado com sucesso.
2025-03-20 20:58:20,133 | INFO | routes.api.produtos | Listando produtos ativos.
2025-03-20 20:58:20,133 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:20,133 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:20,134 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 20:58:41,579 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 20:58:54,007 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 20:58:54,060 | INFO | database | Resetando a instância do Database.
2025-03-20 20:58:54,062 | INFO | app | Inicializando a aplicação Flask.
2025-03-20 20:58:54,062 | DEBUG | app | Configurações carregadas: <Config {'DEBUG': True, 'TESTING': True, 'PROPAGATE_EXCEPTIONS': None, 'SECRET_KEY': 'chamafilho', 'SECRET_KEY_FALLBACKS': None, 'PERMANENT_SESSION_LIFETIME': datetime.timedelta(days=31), 'USE_X_SENDFILE': False, 'TRUSTED_HOSTS': None, 'SERVER_NAME': None, 'APPLICATION_ROOT': '/', 'SESSION_COOKIE_NAME': 'session', 'SESSION_COOKIE_DOMAIN': None, 'SESSION_COOKIE_PATH': None, 'SESSION_COOKIE_HTTPONLY': True, 'SESSION_COOKIE_SECURE': False, 'SESSION_COOKIE_PARTITIONED': False, 'SESSION_COOKIE_SAMESITE': None, 'SESSION_REFRESH_EACH_REQUEST': True, 'MAX_CONTENT_LENGTH': None, 'MAX_FORM_MEMORY_SIZE': 500000, 'MAX_FORM_PARTS': 1000, 'SEND_FILE_MAX_AGE_DEFAULT': None, 'TRAP_BAD_REQUEST_ERRORS': None, 'TRAP_HTTP_EXCEPTIONS': False, 'EXPLAIN_TEMPLATE_LOADING': False, 'PREFERRED_URL_SCHEME': 'http', 'TEMPLATES_AUTO_RELOAD': None, 'MAX_COOKIE_SIZE': 4093, 'PROVIDE_AUTOMATIC_OPTIONS': True, 'BASE_DIR': 'C:\\Users\\tutas\\Documents\\Projetos GitHUB\\store-management-system', 'SQLALCHEMY_DATABASE_URI': 'sqlite:///:memory:', 'SQLALCHEMY_TRACK_MODIFICATIONS': False}>
2025-03-20 20:58:54,062 | INFO | database | Criando nova instância do Database.
2025-03-20 20:58:54,062 | INFO | database | Usando o banco de dados: sqlite:///:memory:
2025-03-20 20:58:54,077 | INFO | database | Registrando modelos e criando tabelas, se necessário.
2025-03-20 20:58:54,081 | INFO | app | Banco de dados configurado e modelos registrados com sucesso.
2025-03-20 20:58:54,089 | INFO | app | Rotas inicializadas com sucesso.
2025-03-20 20:58:54,090 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:54,090 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:54,090 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 20:58:54,091 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:54,091 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:54,511 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 20:58:54,511 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 20:58:54,511 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:58:54,511 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:58:54,650 | INFO | services.utilizadoresmanager | Utilizador admin@email.com autenticado.
2025-03-20 20:58:54,650 | INFO | services.authmanager | Token gerado com sucesso.
2025-03-20 20:58:54,651 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 20:58:54,652 | ERROR | services.authmanager | Tentativa de gerar token, erro: 'Utilizador' object has no attribute 'nome'
2025-03-20 20:59:01,262 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 20:59:01,316 | INFO | database | Resetando a instância do Database.
2025-03-20 20:59:01,317 | INFO | app | Inicializando a aplicação Flask.
2025-03-20 20:59:01,317 | DEBUG | app | Configurações carregadas: <Config {'DEBUG': True, 'TESTING': True, 'PROPAGATE_EXCEPTIONS': None, 'SECRET_KEY': 'chamafilho', 'SECRET_KEY_FALLBACKS': None, 'PERMANENT_SESSION_LIFETIME': datetime.timedelta(days=31), 'USE_X_SENDFILE': False, 'TRUSTED_HOSTS': None, 'SERVER_NAME': None, 'APPLICATION_ROOT': '/', 'SESSION_COOKIE_NAME': 'session', 'SESSION_COOKIE_DOMAIN': None, 'SESSION_COOKIE_PATH': None, 'SESSION_COOKIE_HTTPONLY': True, 'SESSION_COOKIE_SECURE': False, 'SESSION_COOKIE_PARTITIONED': False, 'SESSION_COOKIE_SAMESITE': None, 'SESSION_REFRESH_EACH_REQUEST': True, 'MAX_CONTENT_LENGTH': None, 'MAX_FORM_MEMORY_SIZE': 500000, 'MAX_FORM_PARTS': 1000, 'SEND_FILE_MAX_AGE_DEFAULT': None, 'TRAP_BAD_REQUEST_ERRORS': None, 'TRAP_HTTP_EXCEPTIONS': False, 'EXPLAIN_TEMPLATE_LOADING': False, 'PREFERRED_URL_SCHEME': 'http', 'TEMPLATES_AUTO_RELOAD': None, 'MAX_COOKIE_SIZE': 4093, 'PROVIDE_AUTOMATIC_OPTIONS': True, 'BASE_DIR': 'C:\\Users\\tutas\\Documents\\Projetos GitHUB\\store-management-system', 'SQLALCHEMY_DATABASE_URI': 'sqlite:///:memory:', 'SQLALCHEMY_TRACK_MODIFICATIONS': False}>
2025-03-20 20:59:01,317 | INFO | database | Criando nova instância do Database.
2025-03-20 20:59:01,317 | INFO | database | Usando o banco de dados: sqlite:///:memory:
2025-03-20 20:59:01,332 | INFO | database | Registrando modelos e criando tabelas, se necessário.
2025-03-20 20:59:01,336 | INFO | app | Banco de dados configurado e modelos registrados com sucesso.
2025-03-20 20:59:01,344 | INFO | app | Rotas inicializadas com sucesso.
2025-03-20 20:59:01,344 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:59:01,344 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:59:01,345 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 20:59:01,345 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:59:01,345 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:59:01,779 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 20:59:01,780 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 20:59:01,780 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 20:59:01,780 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 20:59:01,917 | INFO | services.utilizadoresmanager | Utilizador admin@email.com autenticado.
2025-03-20 20:59:01,917 | INFO | services.authmanager | Token gerado com sucesso.
2025-03-20 20:59:01,917 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 20:59:01,918 | ERROR | services.authmanager | Tentativa de gerar token, erro: 'Utilizador' object has no attribute 'nome'
2025-03-20 21:04:31,303 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 21:04:31,357 | INFO | database | Resetando a instância do Database.
2025-03-20 21:04:31,358 | INFO | app | Inicializando a aplicação Flask.
2025-03-20 21:04:31,359 | DEBUG | app | Configurações carregadas: <Config {'DEBUG': True, 'TESTING': True, 'PROPAGATE_EXCEPTIONS': None, 'SECRET_KEY': 'chamafilho', 'SECRET_KEY_FALLBACKS': None, 'PERMANENT_SESSION_LIFETIME': datetime.timedelta(days=31), 'USE_X_SENDFILE': False, 'TRUSTED_HOSTS': None, 'SERVER_NAME': None, 'APPLICATION_ROOT': '/', 'SESSION_COOKIE_NAME': 'session', 'SESSION_COOKIE_DOMAIN': None, 'SESSION_COOKIE_PATH': None, 'SESSION_COOKIE_HTTPONLY': True, 'SESSION_COOKIE_SECURE': False, 'SESSION_COOKIE_PARTITIONED': False, 'SESSION_COOKIE_SAMESITE': None, 'SESSION_REFRESH_EACH_REQUEST': True, 'MAX_CONTENT_LENGTH': None, 'MAX_FORM_MEMORY_SIZE': 500000, 'MAX_FORM_PARTS': 1000, 'SEND_FILE_MAX_AGE_DEFAULT': None, 'TRAP_BAD_REQUEST_ERRORS': None, 'TRAP_HTTP_EXCEPTIONS': False, 'EXPLAIN_TEMPLATE_LOADING': False, 'PREFERRED_URL_SCHEME': 'http', 'TEMPLATES_AUTO_RELOAD': None, 'MAX_COOKIE_SIZE': 4093, 'PROVIDE_AUTOMATIC_OPTIONS': True, 'BASE_DIR': 'C:\\Users\\tutas\\Documents\\Projetos GitHUB\\store-management-system', 'SQLALCHEMY_DATABASE_URI': 'sqlite:///:memory:', 'SQLALCHEMY_TRACK_MODIFICATIONS': False}>
2025-03-20 21:04:31,359 | INFO | database | Criando nova instância do Database.
2025-03-20 21:04:31,359 | INFO | database | Usando o banco de dados: sqlite:///:memory:
2025-03-20 21:04:31,373 | INFO | database | Registrando modelos e criando tabelas, se necessário.
2025-03-20 21:04:31,378 | INFO | app | Banco de dados configurado e modelos registrados com sucesso.
2025-03-20 21:04:31,386 | INFO | app | Rotas inicializadas com sucesso.
2025-03-20 21:04:31,386 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:04:31,386 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:04:31,388 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 21:04:31,388 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:04:31,388 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:04:31,810 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 21:04:31,810 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 21:04:31,811 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:04:31,811 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:04:31,943 | INFO | services.utilizadoresmanager | Utilizador admin@email.com autenticado.
2025-03-20 21:04:31,943 | INFO | services.authmanager | Token gerado com sucesso.
2025-03-20 21:04:31,944 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 21:04:31,945 | ERROR | services.authmanager | Tentativa de gerar token, erro: 'Utilizador' object has no attribute 'nome'
2025-03-20 21:04:31,945 | ERROR | services.authmanager | Tentativa de gerar token, erro: 'Utilizador' object has no attribute 'nome'
2025-03-20 21:04:54,879 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 21:04:54,939 | INFO | database | Resetando a instância do Database.
2025-03-20 21:04:54,940 | INFO | app | Inicializando a aplicação Flask.
2025-03-20 21:04:54,941 | DEBUG | app | Configurações carregadas: <Config {'DEBUG': True, 'TESTING': True, 'PROPAGATE_EXCEPTIONS': None, 'SECRET_KEY': 'chamafilho', 'SECRET_KEY_FALLBACKS': None, 'PERMANENT_SESSION_LIFETIME': datetime.timedelta(days=31), 'USE_X_SENDFILE': False, 'TRUSTED_HOSTS': None, 'SERVER_NAME': None, 'APPLICATION_ROOT': '/', 'SESSION_COOKIE_NAME': 'session', 'SESSION_COOKIE_DOMAIN': None, 'SESSION_COOKIE_PATH': None, 'SESSION_COOKIE_HTTPONLY': True, 'SESSION_COOKIE_SECURE': False, 'SESSION_COOKIE_PARTITIONED': False, 'SESSION_COOKIE_SAMESITE': None, 'SESSION_REFRESH_EACH_REQUEST': True, 'MAX_CONTENT_LENGTH': None, 'MAX_FORM_MEMORY_SIZE': 500000, 'MAX_FORM_PARTS': 1000, 'SEND_FILE_MAX_AGE_DEFAULT': None, 'TRAP_BAD_REQUEST_ERRORS': None, 'TRAP_HTTP_EXCEPTIONS': False, 'EXPLAIN_TEMPLATE_LOADING': False, 'PREFERRED_URL_SCHEME': 'http', 'TEMPLATES_AUTO_RELOAD': None, 'MAX_COOKIE_SIZE': 4093, 'PROVIDE_AUTOMATIC_OPTIONS': True, 'BASE_DIR': 'C:\\Users\\tutas\\Documents\\Projetos GitHUB\\store-management-system', 'SQLALCHEMY_DATABASE_URI': 'sqlite:///:memory:', 'SQLALCHEMY_TRACK_MODIFICATIONS': False}>
2025-03-20 21:04:54,941 | INFO | database | Criando nova instância do Database.
2025-03-20 21:04:54,941 | INFO | database | Usando o banco de dados: sqlite:///:memory:
2025-03-20 21:04:54,957 | INFO | database | Registrando modelos e criando tabelas, se necessário.
2025-03-20 21:04:54,962 | INFO | app | Banco de dados configurado e modelos registrados com sucesso.
2025-03-20 21:04:54,970 | INFO | app | Rotas inicializadas com sucesso.
2025-03-20 21:04:54,970 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:04:54,970 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:04:54,971 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 21:04:54,971 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:04:54,971 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:04:55,374 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 21:04:55,375 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 21:04:55,375 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:04:55,375 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:04:55,505 | INFO | services.utilizadoresmanager | Utilizador admin@email.com autenticado.
2025-03-20 21:04:55,505 | INFO | services.authmanager | Token gerado com sucesso.
2025-03-20 21:04:55,505 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 21:04:55,507 | ERROR | services.authmanager | Tentativa de gerar token, erro: 'Utilizador' object has no attribute 'nome'
2025-03-20 21:04:55,507 | ERROR | services.authmanager | Tentativa de gerar token, erro: 'Utilizador' object has no attribute 'nome'
2025-03-20 21:06:12,639 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 21:06:12,691 | INFO | database | Resetando a instância do Database.
2025-03-20 21:06:12,692 | INFO | app | Inicializando a aplicação Flask.
2025-03-20 21:06:12,692 | DEBUG | app | Configurações carregadas: <Config {'DEBUG': True, 'TESTING': True, 'PROPAGATE_EXCEPTIONS': None, 'SECRET_KEY': 'chamafilho', 'SECRET_KEY_FALLBACKS': None, 'PERMANENT_SESSION_LIFETIME': datetime.timedelta(days=31), 'USE_X_SENDFILE': False, 'TRUSTED_HOSTS': None, 'SERVER_NAME': None, 'APPLICATION_ROOT': '/', 'SESSION_COOKIE_NAME': 'session', 'SESSION_COOKIE_DOMAIN': None, 'SESSION_COOKIE_PATH': None, 'SESSION_COOKIE_HTTPONLY': True, 'SESSION_COOKIE_SECURE': False, 'SESSION_COOKIE_PARTITIONED': False, 'SESSION_COOKIE_SAMESITE': None, 'SESSION_REFRESH_EACH_REQUEST': True, 'MAX_CONTENT_LENGTH': None, 'MAX_FORM_MEMORY_SIZE': 500000, 'MAX_FORM_PARTS': 1000, 'SEND_FILE_MAX_AGE_DEFAULT': None, 'TRAP_BAD_REQUEST_ERRORS': None, 'TRAP_HTTP_EXCEPTIONS': False, 'EXPLAIN_TEMPLATE_LOADING': False, 'PREFERRED_URL_SCHEME': 'http', 'TEMPLATES_AUTO_RELOAD': None, 'MAX_COOKIE_SIZE': 4093, 'PROVIDE_AUTOMATIC_OPTIONS': True, 'BASE_DIR': 'C:\\Users\\tutas\\Documents\\Projetos GitHUB\\store-management-system', 'SQLALCHEMY_DATABASE_URI': 'sqlite:///:memory:', 'SQLALCHEMY_TRACK_MODIFICATIONS': False}>
2025-03-20 21:06:12,693 | INFO | database | Criando nova instância do Database.
2025-03-20 21:06:12,693 | INFO | database | Usando o banco de dados: sqlite:///:memory:
2025-03-20 21:06:12,710 | INFO | database | Registrando modelos e criando tabelas, se necessário.
2025-03-20 21:06:12,714 | INFO | app | Banco de dados configurado e modelos registrados com sucesso.
2025-03-20 21:06:12,724 | INFO | app | Rotas inicializadas com sucesso.
2025-03-20 21:06:12,724 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:12,724 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:12,725 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 21:06:12,725 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:12,725 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:13,186 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 21:06:13,187 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 21:06:13,187 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:13,187 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:13,334 | INFO | services.utilizadoresmanager | Utilizador admin@email.com autenticado.
2025-03-20 21:06:13,334 | INFO | services.authmanager | Token gerado com sucesso.
2025-03-20 21:06:13,336 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 21:06:13,337 | INFO | services.authmanager | Token gerado com sucesso.
2025-03-20 21:06:19,783 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 21:06:19,850 | INFO | database | Resetando a instância do Database.
2025-03-20 21:06:19,851 | INFO | app | Inicializando a aplicação Flask.
2025-03-20 21:06:19,851 | DEBUG | app | Configurações carregadas: <Config {'DEBUG': True, 'TESTING': True, 'PROPAGATE_EXCEPTIONS': None, 'SECRET_KEY': 'chamafilho', 'SECRET_KEY_FALLBACKS': None, 'PERMANENT_SESSION_LIFETIME': datetime.timedelta(days=31), 'USE_X_SENDFILE': False, 'TRUSTED_HOSTS': None, 'SERVER_NAME': None, 'APPLICATION_ROOT': '/', 'SESSION_COOKIE_NAME': 'session', 'SESSION_COOKIE_DOMAIN': None, 'SESSION_COOKIE_PATH': None, 'SESSION_COOKIE_HTTPONLY': True, 'SESSION_COOKIE_SECURE': False, 'SESSION_COOKIE_PARTITIONED': False, 'SESSION_COOKIE_SAMESITE': None, 'SESSION_REFRESH_EACH_REQUEST': True, 'MAX_CONTENT_LENGTH': None, 'MAX_FORM_MEMORY_SIZE': 500000, 'MAX_FORM_PARTS': 1000, 'SEND_FILE_MAX_AGE_DEFAULT': None, 'TRAP_BAD_REQUEST_ERRORS': None, 'TRAP_HTTP_EXCEPTIONS': False, 'EXPLAIN_TEMPLATE_LOADING': False, 'PREFERRED_URL_SCHEME': 'http', 'TEMPLATES_AUTO_RELOAD': None, 'MAX_COOKIE_SIZE': 4093, 'PROVIDE_AUTOMATIC_OPTIONS': True, 'BASE_DIR': 'C:\\Users\\tutas\\Documents\\Projetos GitHUB\\store-management-system', 'SQLALCHEMY_DATABASE_URI': 'sqlite:///:memory:', 'SQLALCHEMY_TRACK_MODIFICATIONS': False}>
2025-03-20 21:06:19,851 | INFO | database | Criando nova instância do Database.
2025-03-20 21:06:19,851 | INFO | database | Usando o banco de dados: sqlite:///:memory:
2025-03-20 21:06:19,868 | INFO | database | Registrando modelos e criando tabelas, se necessário.
2025-03-20 21:06:19,872 | INFO | app | Banco de dados configurado e modelos registrados com sucesso.
2025-03-20 21:06:19,880 | INFO | app | Rotas inicializadas com sucesso.
2025-03-20 21:06:19,881 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:19,881 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:19,881 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 21:06:19,883 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:19,883 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:20,313 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 21:06:20,313 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 21:06:20,314 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:20,314 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:20,447 | INFO | services.utilizadoresmanager | Utilizador admin@email.com autenticado.
2025-03-20 21:06:20,447 | INFO | services.authmanager | Token gerado com sucesso.
2025-03-20 21:06:20,447 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 21:06:20,450 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:20,450 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:20,849 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 21:06:20,849 | INFO | routes.api.auth | Dados recebidos: {'email': 'user@email.com', 'password': '123456'}
2025-03-20 21:06:20,849 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:20,849 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:20,984 | INFO | services.utilizadoresmanager | Utilizador user@email.com autenticado.
2025-03-20 21:06:20,984 | INFO | services.authmanager | Token gerado com sucesso.
2025-03-20 21:06:20,984 | INFO | routes.api.auth | Utilizador autenticado: user@email.com
2025-03-20 21:06:20,986 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:20,986 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:21,383 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 21:06:21,383 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'teste errado'}
2025-03-20 21:06:21,383 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:21,383 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:21,513 | INFO | services.utilizadoresmanager | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-20 21:06:21,513 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-20 21:06:21,516 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:21,516 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:21,926 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 21:06:21,926 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 21:06:21,926 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:21,926 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:22,060 | INFO | services.utilizadoresmanager | Utilizador admin@email.com autenticado.
2025-03-20 21:06:22,060 | INFO | services.authmanager | Token gerado com sucesso.
2025-03-20 21:06:22,061 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 21:06:22,061 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:22,061 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:22,063 | DEBUG | services.authmanager | Token validado com sucesso.
2025-03-20 21:06:22,063 | INFO | services.tokenrevogadomanager | Token revogado: <models.tokenrevogado.TokenRevogado object at 0x000002C898F99E80>
2025-03-20 21:06:22,063 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:22,063 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:22,064 | INFO | routes.api.auth | Logout com sucesso
2025-03-20 21:06:22,067 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:22,067 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:22,468 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 21:06:22,468 | INFO | routes.api.auth | Dados recebidos: {}
2025-03-20 21:06:22,469 | WARNING | routes.api.auth | Tentativa de login sem credenciais fornecidas.
2025-03-20 21:06:22,471 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:22,471 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:22,873 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 21:06:22,873 | INFO | routes.api.auth | Dados recebidos: {'email': 'naoexiste@email.com', 'password': '123456'}
2025-03-20 21:06:22,873 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:22,873 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:22,874 | INFO | services.utilizadoresmanager | Token não gerado, dados não autenticados, email: naoexiste@email.com
2025-03-20 21:06:22,874 | WARNING | routes.api.auth | Falha na autenticação para o email: naoexiste@email.com
2025-03-20 21:06:22,877 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:22,878 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:23,281 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 21:06:23,281 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'senhaerrada'}
2025-03-20 21:06:23,281 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:23,281 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:23,412 | INFO | services.utilizadoresmanager | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-20 21:06:23,412 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-20 21:06:23,415 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:23,415 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:23,813 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 21:06:23,813 | INFO | routes.api.auth | Dados recebidos: {'email': 'email-invalido', 'password': '123456'}
2025-03-20 21:06:23,813 | WARNING | routes.api.auth | Tenativa de login de email envalido.
2025-03-20 21:06:23,816 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:23,816 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:24,215 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:24,215 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:24,614 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 21:06:24,614 | INFO | routes.api.auth | Formato de envio incorreto, não foi JSON
2025-03-20 21:06:24,616 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:24,617 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:25,020 | WARNING | services.authmanager | Tentativa de validar token expirado
2025-03-20 21:06:25,022 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:25,022 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:25,425 | WARNING | services.authmanager | Tentativa de válidar token inválido.
2025-03-20 21:06:25,427 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:25,427 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:25,833 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:25,833 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:26,237 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 21:06:26,237 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 21:06:26,237 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:26,238 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:26,384 | INFO | services.utilizadoresmanager | Utilizador admin@email.com autenticado.
2025-03-20 21:06:26,384 | INFO | services.authmanager | Token gerado com sucesso.
2025-03-20 21:06:26,386 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 21:06:26,386 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:26,386 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:26,387 | DEBUG | services.authmanager | Token validado com sucesso.
2025-03-20 21:06:26,387 | INFO | services.tokenrevogadomanager | Token revogado: <models.tokenrevogado.TokenRevogado object at 0x000002C898FC5E80>
2025-03-20 21:06:26,387 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:26,387 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:26,388 | INFO | routes.api.auth | Logout com sucesso
2025-03-20 21:06:26,388 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:26,388 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:26,391 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:26,392 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:26,803 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 21:06:26,804 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 21:06:26,804 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:26,804 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:26,962 | INFO | services.utilizadoresmanager | Utilizador admin@email.com autenticado.
2025-03-20 21:06:26,962 | INFO | services.authmanager | Token gerado com sucesso.
2025-03-20 21:06:26,962 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 21:06:26,963 | INFO | services.authmanager | Token gerado com sucesso.
2025-03-20 21:06:26,967 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:26,967 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:27,442 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:27,442 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:27,847 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:27,847 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:28,261 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:28,261 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:28,667 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 21:06:28,667 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 21:06:28,667 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:28,667 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:28,800 | INFO | services.utilizadoresmanager | Utilizador admin@email.com autenticado.
2025-03-20 21:06:28,800 | INFO | services.authmanager | Token gerado com sucesso.
2025-03-20 21:06:28,800 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 21:06:28,801 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:28,801 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:28,802 | DEBUG | services.authmanager | Token validado com sucesso.
2025-03-20 21:06:28,802 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:28,802 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:28,805 | INFO | services.categoriamanager | Categoria criada: Fruta
2025-03-20 21:06:28,805 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 21:06:28,805 | INFO | routes.api.categorias | Nova categoria criada Fruta
2025-03-20 21:06:28,808 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:28,808 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:29,226 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 21:06:29,226 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 21:06:29,226 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:29,226 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:29,363 | INFO | services.utilizadoresmanager | Utilizador admin@email.com autenticado.
2025-03-20 21:06:29,364 | INFO | services.authmanager | Token gerado com sucesso.
2025-03-20 21:06:29,364 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 21:06:29,364 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:29,365 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:29,366 | DEBUG | services.authmanager | Token validado com sucesso.
2025-03-20 21:06:29,366 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:29,366 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:29,367 | INFO | services.categoriamanager | Categoria criada: Categoria Teste
2025-03-20 21:06:29,367 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 21:06:29,368 | INFO | routes.api.categorias | Nova categoria criada Categoria Teste
2025-03-20 21:06:29,368 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:29,368 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:29,370 | DEBUG | services.authmanager | Token validado com sucesso.
2025-03-20 21:06:29,370 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:29,370 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:29,370 | INFO | services.produtomanager | Parâmetros recebidos: nome=banana, preco=3.0, quantidade_estoque=10, categoria_id=2
2025-03-20 21:06:29,375 | INFO | services.produtomanager | Produto criado: banana, Preço: 3.0, Estoque: 10
2025-03-20 21:06:29,375 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 21:06:29,375 | INFO | routes.api.produtos | Produto criado com sucesso: {'id': 1, 'nome': 'banana', 'descricao': None, 'preco': 3.0, 'quantidade_estoque': 10, 'ativo': True, 'categoria_id': 2, 'criado_em': datetime.datetime(2025, 3, 20, 21, 6, 29, 373042), 'atualizado_em': datetime.datetime(2025, 3, 20, 21, 6, 29, 373042)}
2025-03-20 21:06:29,377 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:29,377 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:29,781 | DEBUG | routes.api.auth | Rota /api/auth/login chamada.
2025-03-20 21:06:29,781 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 21:06:29,781 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:29,781 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:29,917 | INFO | services.utilizadoresmanager | Utilizador admin@email.com autenticado.
2025-03-20 21:06:29,917 | INFO | services.authmanager | Token gerado com sucesso.
2025-03-20 21:06:29,917 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 21:06:29,918 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:29,918 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:29,918 | DEBUG | services.authmanager | Token validado com sucesso.
2025-03-20 21:06:29,918 | INFO | routes.api.produtos | Listando produtos ativos.
2025-03-20 21:06:29,918 | DEBUG | database | Obtendo uma nova sessão do banco de dados.
2025-03-20 21:06:29,919 | DEBUG | database | Utilizando instância existente do Database.
2025-03-20 21:06:29,920 | INFO | models.abstrata | Objeto convertido para JSON.
