2025-03-19 21:35:10,024 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-19 21:35:10,227 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-19 21:35:10,695 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-19 21:35:10,839 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-19 21:35:10,839 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-19 21:35:11,301 | INFO | routes.api.auth | Dados recebidos: {'email': 'user@email.com', 'password': '123456'}
2025-03-19 21:35:11,458 | INFO | ProdutoService | Utilizador user@email.com autenticado.
2025-03-19 21:35:11,460 | INFO | routes.api.auth | Utilizador autenticado: user@email.com
2025-03-19 21:35:11,903 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'teste errado'}
2025-03-19 21:35:12,033 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-19 21:35:12,033 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-19 21:35:12,465 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-19 21:35:12,595 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-19 21:35:12,595 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-19 21:35:12,598 | ERROR | routes.api.auth | Erro ao validar token: (builtins.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input.
[SQL: INSERT INTO tokens_revogados (token_jti, criado_em) VALUES (?, ?)]
[parameters: [{'token_jti': '83c7d122-dc99-4f4c-a3ee-a8fa831a0d6e'}]]
Traceback (most recent call last):
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1812, in _execute_context
    context = constructor(
              ^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 1477, in _init_compiled
    flattened_processors[key](compiled_params[key])
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\dialects\sqlite\base.py", line 1116, in process
    raise TypeError(
TypeError: SQLite DateTime type only accepts Python datetime and date objects as input.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\routes\api\auth.py", line 88, in logout
    TokenService.adicionar_token_na_blacklist(g.current_user["jti"])
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\services\tokenrevogadomanager.py", line 13, in adicionar_token_na_blacklist
    session.commit()
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2032, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4353, in flush
    self._flush(objects)
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4488, in _flush
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4449, in _flush
    flush_context.execute()
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
           ^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1818, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1812, in _execute_context
    context = constructor(
              ^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 1477, in _init_compiled
    flattened_processors[key](compiled_params[key])
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\dialects\sqlite\base.py", line 1116, in process
    raise TypeError(
sqlalchemy.exc.StatementError: (builtins.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input.
[SQL: INSERT INTO tokens_revogados (token_jti, criado_em) VALUES (?, ?)]
[parameters: [{'token_jti': '83c7d122-dc99-4f4c-a3ee-a8fa831a0d6e'}]]
2025-03-19 21:35:13,133 | INFO | routes.api.auth | Dados recebidos: {}
2025-03-19 21:35:13,133 | WARNING | routes.api.auth | Tentativa de login sem credenciais fornecidas.
2025-03-19 21:35:13,524 | INFO | routes.api.auth | Dados recebidos: {'email': 'naoexiste@email.com', 'password': '123456'}
2025-03-19 21:35:13,525 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: naoexiste@email.com
2025-03-19 21:35:13,525 | WARNING | routes.api.auth | Falha na autenticação para o email: naoexiste@email.com
2025-03-19 21:35:13,914 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'senhaerrada'}
2025-03-19 21:35:14,044 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-19 21:35:14,044 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-19 21:35:14,435 | INFO | routes.api.auth | Dados recebidos: {'email': 'email-invalido', 'password': '123456'}
2025-03-19 21:35:14,435 | WARNING | routes.api.auth | Tenativa de login de email envalido.
2025-03-19 21:35:15,220 | INFO | routes.api.auth | Formato de envio incorreto, não foi JSON
2025-03-19 21:35:16,786 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-19 21:35:16,913 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-19 21:35:16,914 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-19 21:35:16,916 | ERROR | routes.api.auth | Erro ao validar token: (builtins.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input.
[SQL: INSERT INTO tokens_revogados (token_jti, criado_em) VALUES (?, ?)]
[parameters: [{'token_jti': 'fbb37333-156a-4be0-82a3-83f601ee6037'}]]
Traceback (most recent call last):
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1812, in _execute_context
    context = constructor(
              ^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 1477, in _init_compiled
    flattened_processors[key](compiled_params[key])
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\dialects\sqlite\base.py", line 1116, in process
    raise TypeError(
TypeError: SQLite DateTime type only accepts Python datetime and date objects as input.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\routes\api\auth.py", line 88, in logout
    TokenService.adicionar_token_na_blacklist(g.current_user["jti"])
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\services\tokenrevogadomanager.py", line 13, in adicionar_token_na_blacklist
    session.commit()
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2032, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4353, in flush
    self._flush(objects)
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4488, in _flush
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4449, in _flush
    flush_context.execute()
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
           ^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1818, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1812, in _execute_context
    context = constructor(
              ^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 1477, in _init_compiled
    flattened_processors[key](compiled_params[key])
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\dialects\sqlite\base.py", line 1116, in process
    raise TypeError(
sqlalchemy.exc.StatementError: (builtins.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input.
[SQL: INSERT INTO tokens_revogados (token_jti, criado_em) VALUES (?, ?)]
[parameters: [{'token_jti': 'fbb37333-156a-4be0-82a3-83f601ee6037'}]]
2025-03-19 21:35:17,313 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-19 21:35:17,442 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-19 21:35:17,444 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-19 21:35:17,448 | INFO | CategoriaService | Categoria criada: Fruta
2025-03-19 21:35:17,448 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-19 21:35:17,448 | INFO | routes.api.categorias | Nova categoria criada Fruta
2025-03-19 21:35:17,840 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-19 21:35:17,968 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-19 21:35:17,969 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-19 21:35:17,971 | INFO | CategoriaService | Categoria criada: Categoria Teste
2025-03-19 21:35:17,971 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-19 21:35:17,971 | INFO | routes.api.categorias | Nova categoria criada Categoria Teste
2025-03-19 21:35:17,972 | INFO | ProdutoService | Parâmetros recebidos: nome=banana, preco=3.0, quantidade_estoque=10, categoria_id=2
2025-03-19 21:35:17,974 | ERROR | ProdutoService | Erro ao criar produto: (builtins.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input.
[SQL: INSERT INTO produtos (nome, descricao, preco, quantidade_estoque, ativo, categoria_id, criado_em, atualizado_em) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: [{'nome': 'banana', 'preco': 3.0, 'categoria_id': 2, 'quantidade_estoque': 10, 'ativo': True, 'descricao': None}]]
2025-03-19 21:35:17,976 | ERROR | produto_routes | Erro inesperado ao criar produto: Erro ao criar produto
2025-03-19 21:35:18,373 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-19 21:35:18,502 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-19 21:35:18,502 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-19 21:35:18,504 | INFO | produto_routes | Listando produtos ativos.
2025-03-19 21:36:22,468 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-19 21:37:21,452 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-19 21:37:21,533 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-19 21:37:21,938 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-19 21:37:22,070 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-19 21:37:22,070 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-19 21:37:22,073 | ERROR | routes.api.auth | Erro ao validar token: (builtins.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input.
[SQL: INSERT INTO tokens_revogados (token_jti, criado_em) VALUES (?, ?)]
[parameters: [{'token_jti': '2507391e-86cb-4551-b7d3-67a4bfd7db41'}]]
Traceback (most recent call last):
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1812, in _execute_context
    context = constructor(
              ^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 1477, in _init_compiled
    flattened_processors[key](compiled_params[key])
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\dialects\sqlite\base.py", line 1116, in process
    raise TypeError(
TypeError: SQLite DateTime type only accepts Python datetime and date objects as input.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\routes\api\auth.py", line 88, in logout
    TokenService.adicionar_token_na_blacklist(g.current_user["jti"])
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\services\tokenrevogadomanager.py", line 13, in adicionar_token_na_blacklist
    session.commit()
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2032, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4353, in flush
    self._flush(objects)
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4488, in _flush
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4449, in _flush
    flush_context.execute()
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
           ^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1818, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1812, in _execute_context
    context = constructor(
              ^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 1477, in _init_compiled
    flattened_processors[key](compiled_params[key])
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\dialects\sqlite\base.py", line 1116, in process
    raise TypeError(
sqlalchemy.exc.StatementError: (builtins.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input.
[SQL: INSERT INTO tokens_revogados (token_jti, criado_em) VALUES (?, ?)]
[parameters: [{'token_jti': '2507391e-86cb-4551-b7d3-67a4bfd7db41'}]]
2025-03-19 21:39:31,125 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-19 21:39:31,209 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-19 21:39:31,634 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-19 21:39:31,769 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-19 21:39:31,769 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-19 21:39:31,772 | ERROR | routes.api.auth | Erro ao validar token: (builtins.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input.
[SQL: INSERT INTO tokens_revogados (token_jti, criado_em) VALUES (?, ?)]
[parameters: [{'token_jti': 'b7aa89bd-28ed-4c27-ad77-e825d2fe0282'}]]
Traceback (most recent call last):
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1812, in _execute_context
    context = constructor(
              ^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 1477, in _init_compiled
    flattened_processors[key](compiled_params[key])
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\dialects\sqlite\base.py", line 1116, in process
    raise TypeError(
TypeError: SQLite DateTime type only accepts Python datetime and date objects as input.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\routes\api\auth.py", line 88, in logout
    TokenService.adicionar_token_na_blacklist(g.current_user["jti"])
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\services\tokenrevogadomanager.py", line 13, in adicionar_token_na_blacklist
    session.commit()
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2032, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4353, in flush
    self._flush(objects)
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4488, in _flush
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4449, in _flush
    flush_context.execute()
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
           ^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1818, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1812, in _execute_context
    context = constructor(
              ^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 1477, in _init_compiled
    flattened_processors[key](compiled_params[key])
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\venv\Lib\site-packages\sqlalchemy\dialects\sqlite\base.py", line 1116, in process
    raise TypeError(
sqlalchemy.exc.StatementError: (builtins.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input.
[SQL: INSERT INTO tokens_revogados (token_jti, criado_em) VALUES (?, ?)]
[parameters: [{'token_jti': 'b7aa89bd-28ed-4c27-ad77-e825d2fe0282'}]]
2025-03-19 21:41:03,663 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-19 21:41:03,744 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-19 21:41:04,144 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-19 21:41:04,276 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-19 21:41:04,278 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-19 21:41:04,281 | INFO | routes.api.auth | Logout com sucesso
2025-03-19 21:41:15,972 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-19 21:41:16,075 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-19 21:41:16,495 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-19 21:41:16,643 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-19 21:41:16,644 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-19 21:41:17,069 | INFO | routes.api.auth | Dados recebidos: {'email': 'user@email.com', 'password': '123456'}
2025-03-19 21:41:17,214 | INFO | ProdutoService | Utilizador user@email.com autenticado.
2025-03-19 21:41:17,214 | INFO | routes.api.auth | Utilizador autenticado: user@email.com
2025-03-19 21:41:17,683 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'teste errado'}
2025-03-19 21:41:17,904 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-19 21:41:17,905 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-19 21:41:18,424 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-19 21:41:18,579 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-19 21:41:18,579 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-19 21:41:18,586 | INFO | routes.api.auth | Logout com sucesso
2025-03-19 21:41:19,089 | INFO | routes.api.auth | Dados recebidos: {}
2025-03-19 21:41:19,089 | WARNING | routes.api.auth | Tentativa de login sem credenciais fornecidas.
2025-03-19 21:41:19,532 | INFO | routes.api.auth | Dados recebidos: {'email': 'naoexiste@email.com', 'password': '123456'}
2025-03-19 21:41:19,532 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: naoexiste@email.com
2025-03-19 21:41:19,533 | WARNING | routes.api.auth | Falha na autenticação para o email: naoexiste@email.com
2025-03-19 21:41:19,982 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'senhaerrada'}
2025-03-19 21:41:20,134 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-19 21:41:20,134 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-19 21:41:20,587 | INFO | routes.api.auth | Dados recebidos: {'email': 'email-invalido', 'password': '123456'}
2025-03-19 21:41:20,587 | WARNING | routes.api.auth | Tenativa de login de email envalido.
2025-03-19 21:41:21,478 | INFO | routes.api.auth | Formato de envio incorreto, não foi JSON
2025-03-19 21:41:23,231 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-19 21:41:23,380 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-19 21:41:23,380 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-19 21:41:23,382 | INFO | routes.api.auth | Logout com sucesso
2025-03-19 21:41:23,824 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-19 21:41:23,976 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-19 21:41:23,977 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-19 21:41:23,983 | INFO | CategoriaService | Categoria criada: Fruta
2025-03-19 21:41:23,983 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-19 21:41:23,983 | INFO | routes.api.categorias | Nova categoria criada Fruta
2025-03-19 21:41:24,424 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-19 21:41:24,574 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-19 21:41:24,575 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-19 21:41:24,577 | INFO | CategoriaService | Categoria criada: Categoria Teste
2025-03-19 21:41:24,577 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-19 21:41:24,577 | INFO | routes.api.categorias | Nova categoria criada Categoria Teste
2025-03-19 21:41:24,579 | INFO | ProdutoService | Parâmetros recebidos: nome=banana, preco=3.0, quantidade_estoque=10, categoria_id=2
2025-03-19 21:41:24,581 | ERROR | ProdutoService | Erro ao criar produto: (builtins.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input.
[SQL: INSERT INTO produtos (nome, descricao, preco, quantidade_estoque, ativo, categoria_id, criado_em, atualizado_em) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: [{'quantidade_estoque': 10, 'preco': 3.0, 'ativo': True, 'nome': 'banana', 'categoria_id': 2, 'descricao': None}]]
2025-03-19 21:41:24,581 | ERROR | produto_routes | Erro inesperado ao criar produto: Erro ao criar produto
2025-03-19 21:41:25,172 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-19 21:41:25,318 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-19 21:41:25,320 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-19 21:41:25,322 | INFO | produto_routes | Listando produtos ativos.
2025-03-20 11:16:05,704 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 11:16:06,115 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 11:16:07,245 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:16:07,582 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:16:07,583 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:16:08,604 | INFO | routes.api.auth | Dados recebidos: {'email': 'user@email.com', 'password': '123456'}
2025-03-20 11:16:08,989 | INFO | ProdutoService | Utilizador user@email.com autenticado.
2025-03-20 11:16:08,990 | INFO | routes.api.auth | Utilizador autenticado: user@email.com
2025-03-20 11:16:10,008 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'teste errado'}
2025-03-20 11:16:10,363 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-20 11:16:10,364 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-20 11:16:11,306 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:16:11,617 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:16:11,619 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:16:11,625 | INFO | routes.api.auth | Logout com sucesso
2025-03-20 11:16:12,679 | INFO | routes.api.auth | Dados recebidos: {}
2025-03-20 11:16:12,679 | WARNING | routes.api.auth | Tentativa de login sem credenciais fornecidas.
2025-03-20 11:16:13,692 | INFO | routes.api.auth | Dados recebidos: {'email': 'naoexiste@email.com', 'password': '123456'}
2025-03-20 11:16:13,694 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: naoexiste@email.com
2025-03-20 11:16:13,694 | WARNING | routes.api.auth | Falha na autenticação para o email: naoexiste@email.com
2025-03-20 11:16:14,747 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'senhaerrada'}
2025-03-20 11:16:15,051 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-20 11:16:15,052 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-20 11:16:16,056 | INFO | routes.api.auth | Dados recebidos: {'email': 'email-invalido', 'password': '123456'}
2025-03-20 11:16:16,056 | WARNING | routes.api.auth | Tenativa de login de email envalido.
2025-03-20 11:16:18,048 | INFO | routes.api.auth | Formato de envio incorreto, não foi JSON
2025-03-20 11:16:22,450 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:16:22,838 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:16:22,840 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:16:22,845 | INFO | routes.api.auth | Logout com sucesso
2025-03-20 11:16:24,080 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:16:24,495 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:16:24,496 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:16:24,509 | INFO | CategoriaService | Categoria criada: Fruta
2025-03-20 11:16:24,509 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:16:24,512 | INFO | routes.api.categorias | Nova categoria criada Fruta
2025-03-20 11:16:25,700 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:16:26,108 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:16:26,109 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:16:26,115 | INFO | CategoriaService | Categoria criada: Categoria Teste
2025-03-20 11:16:26,115 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:16:26,115 | INFO | routes.api.categorias | Nova categoria criada Categoria Teste
2025-03-20 11:16:26,118 | INFO | ProdutoService | Parâmetros recebidos: nome=banana, preco=3.0, quantidade_estoque=10, categoria_id=2
2025-03-20 11:16:26,124 | ERROR | ProdutoService | Erro ao criar produto: (builtins.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input.
[SQL: INSERT INTO produtos (nome, descricao, preco, quantidade_estoque, ativo, categoria_id, criado_em, atualizado_em) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: [{'nome': 'banana', 'categoria_id': 2, 'quantidade_estoque': 10, 'ativo': True, 'preco': 3.0, 'descricao': None}]]
2025-03-20 11:16:26,125 | ERROR | produto_routes | Erro inesperado ao criar produto: Erro ao criar produto
2025-03-20 11:16:27,917 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:16:28,310 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:16:28,312 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:16:28,317 | INFO | produto_routes | Listando produtos ativos.
2025-03-20 11:17:39,882 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 11:17:40,087 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 11:17:41,107 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:17:41,435 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:17:41,435 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:17:41,448 | INFO | CategoriaService | Categoria criada: Categoria Teste
2025-03-20 11:17:41,448 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:17:41,448 | INFO | routes.api.categorias | Nova categoria criada Categoria Teste
2025-03-20 11:17:41,451 | INFO | ProdutoService | Parâmetros recebidos: nome=banana, preco=3.0, quantidade_estoque=10, categoria_id=1
2025-03-20 11:17:41,457 | ERROR | ProdutoService | Erro ao criar produto: (builtins.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input.
[SQL: INSERT INTO produtos (nome, descricao, preco, quantidade_estoque, ativo, categoria_id, criado_em, atualizado_em) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: [{'categoria_id': 1, 'quantidade_estoque': 10, 'ativo': True, 'nome': 'banana', 'preco': 3.0, 'descricao': None}]]
2025-03-20 11:17:41,458 | ERROR | produto_routes | Erro inesperado ao criar produto: Erro ao criar produto
2025-03-20 11:17:47,326 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 11:17:47,528 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 11:17:48,506 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:17:48,818 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:17:48,819 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:17:48,831 | INFO | CategoriaService | Categoria criada: Categoria Teste
2025-03-20 11:17:48,831 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:17:48,832 | INFO | routes.api.categorias | Nova categoria criada Categoria Teste
2025-03-20 11:17:48,834 | INFO | ProdutoService | Parâmetros recebidos: nome=banana, preco=3.0, quantidade_estoque=10, categoria_id=1
2025-03-20 11:17:48,840 | ERROR | ProdutoService | Erro ao criar produto: (builtins.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input.
[SQL: INSERT INTO produtos (nome, descricao, preco, quantidade_estoque, ativo, categoria_id, criado_em, atualizado_em) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: [{'preco': 3.0, 'nome': 'banana', 'quantidade_estoque': 10, 'categoria_id': 1, 'ativo': True, 'descricao': None}]]
2025-03-20 11:17:48,841 | ERROR | produto_routes | Erro inesperado ao criar produto: Erro ao criar produto
2025-03-20 11:22:58,902 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 11:22:59,124 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 11:23:00,102 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:23:00,448 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:23:00,450 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:23:00,469 | INFO | CategoriaService | Categoria criada: Categoria Teste
2025-03-20 11:23:00,469 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:23:00,469 | INFO | routes.api.categorias | Nova categoria criada Categoria Teste
2025-03-20 11:23:00,473 | INFO | ProdutoService | Parâmetros recebidos: nome=banana, preco=3.0, quantidade_estoque=10, categoria_id=1
2025-03-20 11:23:00,482 | INFO | ProdutoService | Produto criado: banana, Preço: 3.0, Estoque: 10
2025-03-20 11:23:00,482 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:23:06,444 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 11:23:06,667 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 11:23:07,780 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:23:08,111 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:23:08,111 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:23:09,203 | INFO | routes.api.auth | Dados recebidos: {'email': 'user@email.com', 'password': '123456'}
2025-03-20 11:23:09,526 | INFO | ProdutoService | Utilizador user@email.com autenticado.
2025-03-20 11:23:09,526 | INFO | routes.api.auth | Utilizador autenticado: user@email.com
2025-03-20 11:23:10,641 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'teste errado'}
2025-03-20 11:23:11,011 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-20 11:23:11,011 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-20 11:23:12,187 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:23:12,532 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:23:12,532 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:23:12,538 | INFO | routes.api.auth | Logout com sucesso
2025-03-20 11:23:13,619 | INFO | routes.api.auth | Dados recebidos: {}
2025-03-20 11:23:13,620 | WARNING | routes.api.auth | Tentativa de login sem credenciais fornecidas.
2025-03-20 11:23:14,611 | INFO | routes.api.auth | Dados recebidos: {'email': 'naoexiste@email.com', 'password': '123456'}
2025-03-20 11:23:14,613 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: naoexiste@email.com
2025-03-20 11:23:14,613 | WARNING | routes.api.auth | Falha na autenticação para o email: naoexiste@email.com
2025-03-20 11:23:15,604 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'senhaerrada'}
2025-03-20 11:23:15,929 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-20 11:23:15,930 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-20 11:23:16,913 | INFO | routes.api.auth | Dados recebidos: {'email': 'email-invalido', 'password': '123456'}
2025-03-20 11:23:16,913 | WARNING | routes.api.auth | Tenativa de login de email envalido.
2025-03-20 11:23:18,811 | INFO | routes.api.auth | Formato de envio incorreto, não foi JSON
2025-03-20 11:23:22,902 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:23:23,223 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:23:23,223 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:23:23,226 | INFO | routes.api.auth | Logout com sucesso
2025-03-20 11:23:24,190 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:23:24,513 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:23:24,513 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:23:24,523 | INFO | CategoriaService | Categoria criada: Fruta
2025-03-20 11:23:24,523 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:23:24,523 | INFO | routes.api.categorias | Nova categoria criada Fruta
2025-03-20 11:23:25,489 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:23:25,807 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:23:25,807 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:23:25,813 | INFO | CategoriaService | Categoria criada: Categoria Teste
2025-03-20 11:23:25,813 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:23:25,813 | INFO | routes.api.categorias | Nova categoria criada Categoria Teste
2025-03-20 11:23:25,818 | INFO | ProdutoService | Parâmetros recebidos: nome=banana, preco=3.0, quantidade_estoque=10, categoria_id=2
2025-03-20 11:23:25,826 | INFO | ProdutoService | Produto criado: banana, Preço: 3.0, Estoque: 10
2025-03-20 11:23:25,827 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:23:26,919 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:23:27,285 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:23:27,285 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:23:27,288 | INFO | produto_routes | Listando produtos ativos.
2025-03-20 11:23:27,293 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:25:53,980 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 11:25:54,359 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 11:25:55,473 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:25:55,800 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:25:55,802 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:25:56,875 | INFO | routes.api.auth | Dados recebidos: {'email': 'user@email.com', 'password': '123456'}
2025-03-20 11:25:57,201 | INFO | ProdutoService | Utilizador user@email.com autenticado.
2025-03-20 11:25:57,201 | INFO | routes.api.auth | Utilizador autenticado: user@email.com
2025-03-20 11:25:58,374 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'teste errado'}
2025-03-20 11:25:58,685 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-20 11:25:58,685 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-20 11:25:59,682 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:26:00,021 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:26:00,022 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:26:00,030 | INFO | routes.api.auth | Logout com sucesso
2025-03-20 11:26:01,035 | INFO | routes.api.auth | Dados recebidos: {}
2025-03-20 11:26:01,035 | WARNING | routes.api.auth | Tentativa de login sem credenciais fornecidas.
2025-03-20 11:26:01,990 | INFO | routes.api.auth | Dados recebidos: {'email': 'naoexiste@email.com', 'password': '123456'}
2025-03-20 11:26:01,992 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: naoexiste@email.com
2025-03-20 11:26:01,992 | WARNING | routes.api.auth | Falha na autenticação para o email: naoexiste@email.com
2025-03-20 11:26:02,931 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'senhaerrada'}
2025-03-20 11:26:03,263 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-20 11:26:03,263 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-20 11:26:04,213 | INFO | routes.api.auth | Dados recebidos: {'email': 'email-invalido', 'password': '123456'}
2025-03-20 11:26:04,213 | WARNING | routes.api.auth | Tenativa de login de email envalido.
2025-03-20 11:26:06,123 | INFO | routes.api.auth | Formato de envio incorreto, não foi JSON
2025-03-20 11:26:10,191 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:26:10,488 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:26:10,489 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:26:10,492 | INFO | routes.api.auth | Logout com sucesso
2025-03-20 11:26:11,464 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:26:11,770 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:26:11,770 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:26:11,783 | INFO | CategoriaService | Categoria criada: Fruta
2025-03-20 11:26:11,784 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:26:11,784 | INFO | routes.api.categorias | Nova categoria criada Fruta
2025-03-20 11:26:12,752 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:26:13,058 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:26:13,058 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:26:13,068 | INFO | CategoriaService | Categoria criada: Categoria Teste
2025-03-20 11:26:13,068 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:26:13,068 | INFO | routes.api.categorias | Nova categoria criada Categoria Teste
2025-03-20 11:26:13,072 | INFO | ProdutoService | Parâmetros recebidos: nome=banana, preco=3.0, quantidade_estoque=10, categoria_id=2
2025-03-20 11:26:13,080 | INFO | ProdutoService | Produto criado: banana, Preço: 3.0, Estoque: 10
2025-03-20 11:26:13,080 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:26:14,079 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:26:14,383 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:26:14,383 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:26:14,387 | INFO | produto_routes | Listando produtos ativos.
2025-03-20 11:26:14,389 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:28:56,735 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 11:28:56,976 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 11:28:58,063 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:28:58,385 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:28:58,387 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:28:59,404 | INFO | routes.api.auth | Dados recebidos: {'email': 'user@email.com', 'password': '123456'}
2025-03-20 11:28:59,743 | INFO | ProdutoService | Utilizador user@email.com autenticado.
2025-03-20 11:28:59,744 | INFO | routes.api.auth | Utilizador autenticado: user@email.com
2025-03-20 11:29:00,750 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'teste errado'}
2025-03-20 11:29:01,115 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-20 11:29:01,116 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-20 11:29:02,328 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:29:02,706 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:29:02,708 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:29:02,716 | INFO | routes.api.auth | Logout com sucesso
2025-03-20 11:29:03,682 | INFO | routes.api.auth | Dados recebidos: {}
2025-03-20 11:29:03,685 | WARNING | routes.api.auth | Tentativa de login sem credenciais fornecidas.
2025-03-20 11:29:04,644 | INFO | routes.api.auth | Dados recebidos: {'email': 'naoexiste@email.com', 'password': '123456'}
2025-03-20 11:29:04,646 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: naoexiste@email.com
2025-03-20 11:29:04,646 | WARNING | routes.api.auth | Falha na autenticação para o email: naoexiste@email.com
2025-03-20 11:29:05,645 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'senhaerrada'}
2025-03-20 11:29:06,002 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-20 11:29:06,002 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-20 11:29:07,063 | INFO | routes.api.auth | Dados recebidos: {'email': 'email-invalido', 'password': '123456'}
2025-03-20 11:29:07,063 | WARNING | routes.api.auth | Tenativa de login de email envalido.
2025-03-20 11:29:09,042 | INFO | routes.api.auth | Formato de envio incorreto, não foi JSON
2025-03-20 11:29:13,172 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:29:13,498 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:29:13,498 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:29:13,503 | INFO | routes.api.auth | Logout com sucesso
2025-03-20 11:29:14,488 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:29:14,825 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:29:14,826 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:29:14,836 | INFO | CategoriaService | Categoria criada: Fruta
2025-03-20 11:29:14,836 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:29:14,838 | INFO | routes.api.categorias | Nova categoria criada Fruta
2025-03-20 11:29:15,836 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:29:16,164 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:29:16,164 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:29:16,171 | INFO | CategoriaService | Categoria criada: Categoria Teste
2025-03-20 11:29:16,171 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:29:16,171 | INFO | routes.api.categorias | Nova categoria criada Categoria Teste
2025-03-20 11:29:16,174 | INFO | ProdutoService | Parâmetros recebidos: nome=banana, preco=3.0, quantidade_estoque=10, categoria_id=2
2025-03-20 11:29:16,181 | INFO | ProdutoService | Produto criado: banana, Preço: 3.0, Estoque: 10
2025-03-20 11:29:16,181 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:29:17,206 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:29:17,548 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:29:17,548 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:29:17,552 | INFO | produto_routes | Listando produtos ativos.
2025-03-20 11:29:17,558 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:31:30,935 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 11:31:31,173 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 11:31:32,162 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:31:32,462 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:31:32,463 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:31:33,448 | INFO | routes.api.auth | Dados recebidos: {'email': 'user@email.com', 'password': '123456'}
2025-03-20 11:31:33,766 | INFO | ProdutoService | Utilizador user@email.com autenticado.
2025-03-20 11:31:33,766 | INFO | routes.api.auth | Utilizador autenticado: user@email.com
2025-03-20 11:31:34,734 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'teste errado'}
2025-03-20 11:31:35,066 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-20 11:31:35,066 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-20 11:31:36,130 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:31:36,441 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:31:36,442 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:31:36,449 | INFO | routes.api.auth | Logout com sucesso
2025-03-20 11:31:37,419 | INFO | routes.api.auth | Dados recebidos: {}
2025-03-20 11:31:37,419 | WARNING | routes.api.auth | Tentativa de login sem credenciais fornecidas.
2025-03-20 11:31:38,369 | INFO | routes.api.auth | Dados recebidos: {'email': 'naoexiste@email.com', 'password': '123456'}
2025-03-20 11:31:38,370 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: naoexiste@email.com
2025-03-20 11:31:38,370 | WARNING | routes.api.auth | Falha na autenticação para o email: naoexiste@email.com
2025-03-20 11:31:39,343 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'senhaerrada'}
2025-03-20 11:31:39,647 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-20 11:31:39,649 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-20 11:31:40,595 | INFO | routes.api.auth | Dados recebidos: {'email': 'email-invalido', 'password': '123456'}
2025-03-20 11:31:40,595 | WARNING | routes.api.auth | Tenativa de login de email envalido.
2025-03-20 11:31:42,485 | INFO | routes.api.auth | Formato de envio incorreto, não foi JSON
2025-03-20 11:31:46,387 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:31:46,689 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:31:46,690 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:31:46,693 | INFO | routes.api.auth | Logout com sucesso
2025-03-20 11:31:47,640 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:31:47,956 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:31:47,956 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:31:47,965 | INFO | CategoriaService | Categoria criada: Fruta
2025-03-20 11:31:47,965 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:31:47,965 | INFO | routes.api.categorias | Nova categoria criada Fruta
2025-03-20 11:31:48,899 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:31:49,199 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:31:49,200 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:31:49,206 | INFO | CategoriaService | Categoria criada: Categoria Teste
2025-03-20 11:31:49,269 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:31:49,269 | INFO | routes.api.categorias | Nova categoria criada Categoria Teste
2025-03-20 11:31:49,271 | INFO | ProdutoService | Parâmetros recebidos: nome=banana, preco=3.0, quantidade_estoque=10, categoria_id=2
2025-03-20 11:31:49,279 | INFO | ProdutoService | Produto criado: banana, Preço: 3.0, Estoque: 10
2025-03-20 11:31:49,280 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:31:50,224 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:31:50,567 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:31:50,568 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:31:50,570 | INFO | produto_routes | Listando produtos ativos.
2025-03-20 11:31:50,575 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:51:37,183 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 11:51:37,460 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 11:51:38,454 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:51:38,779 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:51:38,781 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:51:39,931 | INFO | routes.api.auth | Dados recebidos: {'email': 'user@email.com', 'password': '123456'}
2025-03-20 11:51:40,262 | INFO | ProdutoService | Utilizador user@email.com autenticado.
2025-03-20 11:51:40,263 | INFO | routes.api.auth | Utilizador autenticado: user@email.com
2025-03-20 11:51:41,364 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'teste errado'}
2025-03-20 11:51:41,757 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-20 11:51:41,758 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-20 11:51:42,773 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:51:43,100 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:51:43,101 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:51:43,107 | INFO | routes.api.auth | Logout com sucesso
2025-03-20 11:51:44,119 | INFO | routes.api.auth | Dados recebidos: {}
2025-03-20 11:51:44,119 | WARNING | routes.api.auth | Tentativa de login sem credenciais fornecidas.
2025-03-20 11:51:45,147 | INFO | routes.api.auth | Dados recebidos: {'email': 'naoexiste@email.com', 'password': '123456'}
2025-03-20 11:51:45,147 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: naoexiste@email.com
2025-03-20 11:51:45,150 | WARNING | routes.api.auth | Falha na autenticação para o email: naoexiste@email.com
2025-03-20 11:51:46,163 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'senhaerrada'}
2025-03-20 11:51:46,489 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-20 11:51:46,489 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-20 11:51:47,544 | INFO | routes.api.auth | Dados recebidos: {'email': 'email-invalido', 'password': '123456'}
2025-03-20 11:51:47,544 | WARNING | routes.api.auth | Tenativa de login de email envalido.
2025-03-20 11:51:49,603 | INFO | routes.api.auth | Formato de envio incorreto, não foi JSON
2025-03-20 11:51:53,723 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:51:54,123 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:51:54,124 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:51:54,130 | INFO | routes.api.auth | Logout com sucesso
2025-03-20 11:51:55,115 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:51:55,447 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:51:55,449 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:51:55,461 | INFO | CategoriaService | Categoria criada: Fruta
2025-03-20 11:51:55,461 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:51:55,462 | INFO | routes.api.categorias | Nova categoria criada Fruta
2025-03-20 11:51:56,457 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:51:56,792 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:51:56,794 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:51:56,802 | INFO | CategoriaService | Categoria criada: Categoria Teste
2025-03-20 11:51:56,802 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:51:56,803 | INFO | routes.api.categorias | Nova categoria criada Categoria Teste
2025-03-20 11:51:56,805 | INFO | ProdutoService | Parâmetros recebidos: nome=banana, preco=3.0, quantidade_estoque=10, categoria_id=2
2025-03-20 11:51:56,815 | INFO | ProdutoService | Produto criado: banana, Preço: 3.0, Estoque: 10
2025-03-20 11:51:56,817 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:51:56,817 | INFO | routes.api.produtos | Produto criado com sucesso: {'id': 1, 'nome': 'banana', 'descricao': None, 'preco': 3.0, 'quantidade_estoque': 10, 'ativo': True, 'categoria_id': 2, 'criado_em': datetime.datetime(2025, 3, 20, 11, 51, 56, 811956), 'atualizado_em': datetime.datetime(2025, 3, 20, 11, 51, 56, 811956)}
2025-03-20 11:51:57,841 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:51:58,185 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:51:58,185 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:51:58,188 | INFO | routes.api.produtos | Listando produtos ativos.
2025-03-20 11:51:58,195 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 11:56:10,624 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 11:56:10,964 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 11:56:11,976 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:56:12,342 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:56:12,343 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:56:12,353 | INFO | routes.api.auth | Logout com sucesso
2025-03-20 11:56:19,699 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 11:56:19,954 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 11:56:20,995 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:56:21,342 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:56:21,344 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:56:22,289 | INFO | routes.api.auth | Dados recebidos: {'email': 'user@email.com', 'password': '123456'}
2025-03-20 11:56:22,678 | INFO | ProdutoService | Utilizador user@email.com autenticado.
2025-03-20 11:56:22,679 | INFO | routes.api.auth | Utilizador autenticado: user@email.com
2025-03-20 11:56:23,621 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'teste errado'}
2025-03-20 11:56:23,972 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-20 11:56:23,972 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-20 11:56:24,947 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:56:25,267 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:56:25,269 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:56:25,275 | INFO | routes.api.auth | Logout com sucesso
2025-03-20 11:56:26,230 | INFO | routes.api.auth | Dados recebidos: {}
2025-03-20 11:56:26,230 | WARNING | routes.api.auth | Tentativa de login sem credenciais fornecidas.
2025-03-20 11:56:27,265 | INFO | routes.api.auth | Dados recebidos: {'email': 'naoexiste@email.com', 'password': '123456'}
2025-03-20 11:56:27,266 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: naoexiste@email.com
2025-03-20 11:56:27,266 | WARNING | routes.api.auth | Falha na autenticação para o email: naoexiste@email.com
2025-03-20 11:56:28,349 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'senhaerrada'}
2025-03-20 11:56:28,822 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-20 11:56:28,822 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-20 11:56:29,791 | INFO | routes.api.auth | Dados recebidos: {'email': 'email-invalido', 'password': '123456'}
2025-03-20 11:56:29,791 | WARNING | routes.api.auth | Tenativa de login de email envalido.
2025-03-20 11:56:31,723 | INFO | routes.api.auth | Formato de envio incorreto, não foi JSON
2025-03-20 11:56:35,925 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:56:36,251 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:56:36,252 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:56:36,255 | INFO | routes.api.auth | Logout com sucesso
2025-03-20 11:56:37,232 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:56:37,554 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:56:37,555 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:57:55,020 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 11:57:55,242 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 11:57:56,281 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:57:56,611 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:57:56,612 | ERROR | routes.api.auth | Erro inesperado no login: 'Utilizador' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\routes\api\auth.py", line 51, in login
    access_token, refresh_token = AuthService.gerar_tokens(utilizador)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\services\authmanager.py", line 20, in gerar_tokens
    "id": utilizador["id"],
         ~~~~~~~~~~^^^^^^
TypeError: 'Utilizador' object is not subscriptable
2025-03-20 11:58:18,301 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 11:58:18,504 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 11:58:19,488 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:58:19,926 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:58:19,926 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 11:59:12,986 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 11:59:13,179 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 11:59:14,227 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 11:59:14,568 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 11:59:14,569 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 12:03:03,033 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 12:03:03,232 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 12:03:04,181 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 12:03:04,495 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 12:03:04,495 | ERROR | routes.api.auth | Erro inesperado no login: 'Utilizador' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\routes\api\auth.py", line 51, in login
    access_token, refresh_token = AuthService.gerar_tokens(utilizador)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\services\authmanager.py", line 20, in gerar_tokens
    "id": utilizador["id"],
         ~~~~~~~~~~^^^^^^
TypeError: 'Utilizador' object is not subscriptable
2025-03-20 12:04:11,099 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 12:04:11,305 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 12:04:12,316 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 12:04:12,643 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 12:04:12,644 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 12:09:19,638 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 12:09:19,907 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 12:09:20,871 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 12:09:21,190 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 12:09:21,190 | ERROR | routes.api.auth | Erro inesperado no login: 'Utilizador' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\routes\api\auth.py", line 51, in login
    access_token, refresh_token = AuthService.gerar_tokens(utilizador)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\services\authmanager.py", line 20, in gerar_tokens
    "id": utilizador["id"],
          ~~~~~~~~~~^^^^^^
TypeError: 'Utilizador' object is not subscriptable
2025-03-20 12:10:52,278 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 12:10:52,523 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 12:10:53,525 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 12:10:53,849 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 12:10:53,855 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 12:14:26,379 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 12:14:26,572 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 12:14:27,569 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 12:14:27,887 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 12:14:27,888 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 12:16:25,921 | INFO | models.abstrata | Classe Abstrata iniciada
2025-03-20 12:16:26,151 | INFO | models.abstrata | Tabelas criadas para testes.
2025-03-20 12:16:27,214 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 12:16:27,545 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 12:16:27,546 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 12:16:28,599 | INFO | routes.api.auth | Dados recebidos: {'email': 'user@email.com', 'password': '123456'}
2025-03-20 12:16:28,931 | INFO | ProdutoService | Utilizador user@email.com autenticado.
2025-03-20 12:16:28,933 | INFO | routes.api.auth | Utilizador autenticado: user@email.com
2025-03-20 12:16:29,891 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'teste errado'}
2025-03-20 12:16:30,219 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-20 12:16:30,220 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-20 12:16:31,201 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 12:16:31,531 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 12:16:31,531 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 12:16:31,540 | INFO | routes.api.auth | Logout com sucesso
2025-03-20 12:16:32,565 | INFO | routes.api.auth | Dados recebidos: {}
2025-03-20 12:16:32,565 | WARNING | routes.api.auth | Tentativa de login sem credenciais fornecidas.
2025-03-20 12:16:33,610 | INFO | routes.api.auth | Dados recebidos: {'email': 'naoexiste@email.com', 'password': '123456'}
2025-03-20 12:16:33,612 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: naoexiste@email.com
2025-03-20 12:16:33,612 | WARNING | routes.api.auth | Falha na autenticação para o email: naoexiste@email.com
2025-03-20 12:16:34,614 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': 'senhaerrada'}
2025-03-20 12:16:34,938 | INFO | ProdutoService | Token não gerado, dados não autenticados, email: admin@email.com
2025-03-20 12:16:34,938 | WARNING | routes.api.auth | Falha na autenticação para o email: admin@email.com
2025-03-20 12:16:35,982 | INFO | routes.api.auth | Dados recebidos: {'email': 'email-invalido', 'password': '123456'}
2025-03-20 12:16:35,982 | WARNING | routes.api.auth | Tenativa de login de email envalido.
2025-03-20 12:16:38,011 | INFO | routes.api.auth | Formato de envio incorreto, não foi JSON
2025-03-20 12:16:42,278 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 12:16:42,615 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 12:16:42,616 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 12:16:42,619 | INFO | routes.api.auth | Logout com sucesso
2025-03-20 12:16:43,652 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 12:16:44,002 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 12:16:44,003 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 12:16:48,178 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 12:16:48,532 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 12:16:48,533 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 12:16:48,545 | INFO | CategoriaService | Categoria criada: Fruta
2025-03-20 12:16:48,546 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 12:16:48,546 | INFO | routes.api.categorias | Nova categoria criada Fruta
2025-03-20 12:16:49,663 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 12:16:50,021 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 12:16:50,022 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 12:16:50,031 | INFO | CategoriaService | Categoria criada: Categoria Teste
2025-03-20 12:16:50,032 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 12:16:50,032 | INFO | routes.api.categorias | Nova categoria criada Categoria Teste
2025-03-20 12:16:50,035 | INFO | ProdutoService | Parâmetros recebidos: nome=banana, preco=3.0, quantidade_estoque=10, categoria_id=2
2025-03-20 12:16:50,047 | INFO | ProdutoService | Produto criado: banana, Preço: 3.0, Estoque: 10
2025-03-20 12:16:50,048 | INFO | models.abstrata | Objeto convertido para JSON.
2025-03-20 12:16:50,048 | INFO | routes.api.produtos | Produto criado com sucesso: {'id': 1, 'nome': 'banana', 'descricao': None, 'preco': 3.0, 'quantidade_estoque': 10, 'ativo': True, 'categoria_id': 2, 'criado_em': datetime.datetime(2025, 3, 20, 12, 16, 50, 42963), 'atualizado_em': datetime.datetime(2025, 3, 20, 12, 16, 50, 42963)}
2025-03-20 12:16:51,149 | INFO | routes.api.auth | Dados recebidos: {'email': 'admin@email.com', 'password': '123456'}
2025-03-20 12:16:51,535 | INFO | ProdutoService | Utilizador admin@email.com autenticado.
2025-03-20 12:16:51,536 | INFO | routes.api.auth | Utilizador autenticado: admin@email.com
2025-03-20 12:16:51,540 | INFO | routes.api.produtos | Listando produtos ativos.
2025-03-20 12:16:51,545 | INFO | models.abstrata | Objeto convertido para JSON.
